"""
Concepts Database: Classical Machine Learning & Optimization (35 Concepts)
"""

ML_CONCEPTS = [
    {
        "id": "concept_features_labels",
        "title": "Features (Inputs) & Labels (Targets)",
        "topic_id": "ml_linear",
        "topic_label": "Linear Regression & Core ML Concepts",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Features (Input attributes x) & Labels (Target outcome y)",
        "def": "Features ($x$) are the quantifiable input variables describing an example; a label ($y$) is the true target value or outcome the model is tasked with predicting.",
        "formula": "$$\\mathcal{D} = \\{(x_1, y_1), (x_2, y_2), \\dots, (x_n, y_n)\\}, \\quad x_i \\in \\mathbb{R}^d, \\; y_i \\in \\mathcal{Y}$$",
        "logic": "Google ML Crash Course Principle: High-performing models require informative, discriminative features. If features lack a true causal or statistical link to the label, no model architecture can overcome the lack of signal.",
        "example": "Spam filtering: Features include email length, sender domain reputation, and word frequency of 'urgent'; the label $y \\in \\{0, 1\\}$ indicates whether the email is spam.",
        "tags": ["Features", "Labels", "Supervised Learning", "ML Fundamentals"]
    },
    {
        "id": "concept_weights_bias",
        "title": "Weights (Slopes) & Bias (Intercept)",
        "topic_id": "ml_linear",
        "topic_label": "Linear Regression & Core ML Concepts",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Weights (Slopes w) & Bias (Intercept b)",
        "def": "Weights ($w$) are the learned coefficients representing the relative importance of each feature; the bias ($b$) is an offset determining the prediction when all feature inputs are zero.",
        "formula": "$$\\hat{y} = w_1 x_1 + w_2 x_2 + \\dots + w_d x_d + b = w^T x + b$$",
        "logic": "Bias provides the model with an essential degree of freedom to shift the linear hyperplane away from the origin $(0, 0)$. Without a bias term, a model is artificially constrained to predict 0 whenever features equal 0.",
        "example": "Cricket chirps to temperature (Google MLCC classic): Weight $w=0.05$ scales chirps per minute to temperature, and bias $b=40$ sets the baseline freezing temperature when crickets are silent.",
        "tags": ["Weights", "Bias", "Linear Regression", "Model Parameters"]
    },
    {
        "id": "concept_labeled_unlabeled",
        "title": "Labeled vs Unlabeled Examples",
        "topic_id": "ml_linear",
        "topic_label": "Linear Regression & Core ML Concepts",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Labeled vs Unlabeled Examples",
        "def": "Labeled examples include both input features and the true ground-truth outcome $(x, y)$, used during training. Unlabeled examples contain only input features $(x, ?)$, used during inference/prediction.",
        "formula": "$$\\mathcal{D}_{\\text{labeled}} = \\{(x_i, y_i)\\}_{i=1}^N, \\quad \\mathcal{D}_{\\text{unlabeled}} = \\{x_j\\}_{j=1}^M \\implies \\hat{y}_j = f(x_j)$$",
        "logic": "Unlabeled data is abundant and inexpensive to collect; human ground-truth labels are expensive and scarce. Semi-supervised learning and self-supervised pre-training leverage unlabeled data to learn rich representations.",
        "example": "Medical imaging: 1,000 X-rays labeled by expert radiologists with cancer diagnoses (labeled); 10,000,000 raw unannotated hospital scans (unlabeled).",
        "tags": ["Data Types", "Supervised Learning", "Unsupervised Learning"]
    },
    {
        "id": "concept_normal_equation",
        "title": "Analytical Solution (The Normal Equation)",
        "topic_id": "ml_linear",
        "topic_label": "Linear Regression & Core ML Concepts",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Analytical Solution (Closed-form Normal Equation)",
        "def": "The closed-form mathematical equation that directly calculates the exact weight vector minimizing OLS residual sum of squares without iterative gradient descent.",
        "formula": "$$w^* = (X^T X)^{-1} X^T y$$",
        "logic": "Setting the gradient of RSS to zero $\\nabla_w \\|y - Xw\\|^2 = 0$ yields the Normal Equation. While exact, it requires inverting an $X^T X$ matrix ($O(d^3)$ compute), making it impractical when feature count $d > 10,000$.",
        "example": "Fitting a quadratic curve on 50 lab measurements: Computing $(X^T X)^{-1} X^T y$ executes in 0.2 milliseconds in NumPy, yielding the globally optimal curve instantly.",
        "tags": ["Normal Equation", "Closed Form", "OLS", "Linear Algebra"]
    },
    {
        "id": "concept_model_inference",
        "title": "Model Inference & Serving",
        "topic_id": "ml_linear",
        "topic_label": "Linear Regression & Core ML Concepts",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Inference / Prediction (Computing y' from new inputs)",
        "def": "The operational phase where a previously trained model with fixed frozen weights accepts brand-new, unseen inputs and outputs a prediction $\\hat{y}$.",
        "formula": "$$\\hat{y}_{\\text{new}} = f(x_{\\text{new}}; w^*, b^*) = \\sigma(w^{*T} x_{\\text{new}} + b^*)$$",
        "logic": "Training is compute-bound and can take hours or days; inference is strictly latency-bound and must typically return predictions in under 10 to 50 milliseconds in production web services.",
        "example": "Ride-share price estimate: When a user enters their destination in the app, the production model evaluates distance, weather, driver density, and historical surge in 12ms to show the fare.",
        "tags": ["Inference", "Production Serving", "Prediction"]
    },
    {
        "id": "concept_squared_loss",
        "title": "Squared Loss & L2 Loss",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Squared Loss / L2 Loss (Penalizes big mistakes harshly)",
        "def": "A loss function measuring the square of the difference between an individual true label and the model prediction.",
        "formula": "$$L_2(y, \\hat{y}) = (y - \\hat{y})^2$$",
        "logic": "Squaring penalties makes large mistakes exponentially more expensive than small mistakes. An error of 10 units produces a penalty of 100, whereas an error of 2 units produces only 4.",
        "example": "Predicting flight arrival delays: If a flight arrives 2 minutes late, loss is 4. If it arrives 30 minutes late, loss is 900, forcing the model to aggressively avoid massive mispredictions.",
        "tags": ["Squared Loss", "L2 Loss", "Loss Functions"]
    },
    {
        "id": "concept_mse",
        "title": "Mean Squared Error (MSE)",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Mean Squared Error (MSE across all training examples)",
        "def": "The average of the squared differences between true labels and predictions across the entire dataset.",
        "formula": "$$\\text{MSE} = \\frac{1}{n} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2$$",
        "logic": "The most common default regression loss. Smooth and continuously differentiable everywhere, providing clean linear gradients that decrease naturally as the model nears the minimum.",
        "example": "Housing price prediction: Evaluating how close home valuations are across 10,000 houses sold in the past quarter.",
        "tags": ["MSE", "Regression Metric", "Loss Function"]
    },
    {
        "id": "concept_mae",
        "title": "Mean Absolute Error (MAE & L1 Loss)",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Mean Absolute Error (MAE / L1 loss, outlier resistant)",
        "def": "The average of the absolute differences between true labels and predictions across all examples.",
        "formula": "$$\\text{MAE} = \\frac{1}{n} \\sum_{i=1}^n |y_i - \\hat{y}_i|$$",
        "logic": "Linear error penalty makes MAE exceptionally robust to extreme outliers compared to MSE. However, its derivative is discontinuous at 0, requiring subgradient methods.",
        "example": "Estimating hospital wait times: Rare multi-hour emergency surges won't wildly distort the baseline wait-time model because MAE treats a 10-hour error linearly rather than squaring it.",
        "tags": ["MAE", "L1 Loss", "Outlier Resistant", "Regression"]
    },
    {
        "id": "concept_rmse",
        "title": "Root Mean Squared Error (RMSE)",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Root Mean Squared Error (RMSE, interpretable in original units)",
        "def": "The square root of the Mean Squared Error, bringing the error metric back into the exact same physical units as the original target variable.",
        "formula": "$$\\text{RMSE} = \\sqrt{\\frac{1}{n} \\sum_{i=1}^n (y_i - \\hat{y}_i)^2}$$",
        "logic": "While MSE expresses error in squared units (e.g. $\\text{dollars}^2$), RMSE expresses error in dollars, making it immediately interpretable to business stakeholders while preserving MSE's sensitivity to large errors.",
        "example": "Predicting salary: An MSE of 25,000,000 is hard to interpret; taking the square root gives an RMSE of $5,000, clearly stating the average spread in real currency.",
        "tags": ["RMSE", "Evaluation Metric", "Regression"]
    },
    {
        "id": "concept_huber_loss",
        "title": "Huber Loss (Smooth Robust Loss)",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Huber Loss (Smooth piecewise hybrid of L1 and L2)",
        "def": "A robust piecewise loss function that behaves quadratically (MSE) for small errors and linearly (MAE) for large errors beyond a threshold $\\delta$.",
        "formula": "$$L_\\delta(y, \\hat{y}) = \\begin{cases} \\frac{1}{2}(y - \\hat{y})^2 & \\text{if } |y - \\hat{y}| \\le \\delta \\\\ \\delta |y - \\hat{y}| - \\frac{1}{2}\\delta^2 & \\text{otherwise} \\end{cases}$$",
        "logic": "Combines the best of both worlds: smooth quadratic convergence near the optimum (unlike MAE) and robust linear bounded gradients for extreme outliers (unlike MSE).",
        "example": "Self-driving car trajectory prediction: Standard sensor noise follows MSE, while unpredictable sensor glitches (outliers) are handled gracefully by the linear slope.",
        "tags": ["Huber Loss", "Robust Regression", "Smooth Loss"]
    },
    {
        "id": "concept_binary_cross_entropy",
        "title": "Log Loss & Binary Cross-Entropy",
        "topic_id": "ml_loss",
        "topic_label": "Loss Functions (L1, L2, MSE, MAE, Log Loss)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Log Loss / Binary Cross-Entropy (For probabilistic classification)",
        "def": "The standard convex loss function for binary classification, measuring the performance of a model whose output is a probability value between 0 and 1.",
        "formula": "$$\\mathcal{L}_{\\text{BCE}} = -\\frac{1}{n} \\sum_{i=1}^n \\left[ y_i \\ln(\\hat{y}_i) + (1 - y_i) \\ln(1 - \\hat{y}_i) \\right]$$",
        "logic": "Derived from the negative log-likelihood of a Bernoulli distribution. It cancels out the plateau derivative of Sigmoid, preventing gradient vanishing when predictions are wrong.",
        "example": "Predicting loan default: If a borrower defaults ($y=1$) and the model predicted 90% risk, loss is low (0.105); if the model predicted only 1% risk, loss is severe (4.605).",
        "tags": ["Log Loss", "Cross-Entropy", "Binary Classification"]
    },
    {
        "id": "concept_learning_rate",
        "title": "Learning Rate & Step Size",
        "topic_id": "ml_opt",
        "topic_label": "Gradient Descent & Hyperparameters",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Learning Rate (Step size taken per iteration)",
        "def": "A scalar hyperparameter ($\\eta$) that scales the magnitude of parameter updates along the negative gradient direction during gradient descent.",
        "formula": "$$w^{(t+1)} = w^{(t)} - \\eta \\cdot \\nabla_w \\mathcal{L}(w^{(t)})$$",
        "logic": "Google ML Crash Course Principle: If $\\eta$ is too small, training crawls at a glacial pace; if $\\eta$ is too large, optimization overshoots the valley, oscillates violently, and diverges into NaNs.",
        "example": "Tuning a neural net: A learning rate of 1.0 explodes the loss to infinity; 0.000001 barely changes the loss after 10 epochs; a tuned rate of 0.001 converges smoothly.",
        "tags": ["Learning Rate", "Gradient Descent", "Hyperparameter Tuning"]
    },
    {
        "id": "concept_batch_sizes",
        "title": "Batch Size (Full Batch vs Mini-Batch vs SGD)",
        "topic_id": "ml_opt",
        "topic_label": "Gradient Descent & Hyperparameters",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Batch Size (Full Batch vs Mini-Batch vs Single-Sample SGD)",
        "def": "The number of training examples evaluated in a single step to compute the gradient before updating model weights.",
        "formula": "$$\\nabla \\mathcal{L}_{\\text{mini}} = \\frac{1}{B} \\sum_{i=1}^B \\nabla \\mathcal{L}_i(w), \\quad B \\in \\{32, 64, 128, 256, 512\\}$$",
        "logic": "Full batch ($B=N$) computes exact gradients but is too slow for millions of rows. Pure SGD ($B=1$) is noisy and underutilizes GPU parallelism. Mini-batch ($B=32$ to $512$) provides optimal GPU tensor throughput and beneficial gradient stochasticity.",
        "example": "Training on 1,000,000 images: Mini-batch size 128 executes ~7,812 weight updates per epoch, maximizing memory bandwidth on an NVIDIA H100.",
        "tags": ["Batch Size", "Mini-Batch", "SGD", "GPU Optimization"]
    },
    {
        "id": "concept_epochs",
        "title": "Epochs & Training Passes",
        "topic_id": "ml_opt",
        "topic_label": "Gradient Descent & Hyperparameters",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Epochs (Full passes over the entire training set)",
        "def": "One complete presentation of every single example in the training dataset to the learning algorithm.",
        "formula": "$$\\text{Iterations per Epoch} = \\frac{N_{\\text{samples}}}{\\text{Batch Size}}$$",
        "logic": "A model requires multiple epochs to converge because individual gradient steps only update weights incrementally. Too few epochs cause underfitting; too many cause overfitting.",
        "example": "A dataset of 100,000 records trained with batch size 100 performs 1,000 iterations per epoch. Training for 20 epochs totals 20,000 weight update steps.",
        "tags": ["Epochs", "Training Iterations", "Deep Learning Training"]
    },
    {
        "id": "concept_convergence",
        "title": "Loss Convergence & Stopping Criteria",
        "topic_id": "ml_opt",
        "topic_label": "Gradient Descent & Hyperparameters",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Convergence (When loss plateaus and stops decreasing)",
        "def": "The state where successive optimization iterations fail to produce meaningful reductions in error, indicating that the model has reached a local or global minimum.",
        "formula": "$$|\\mathcal{L}^{(t)} - \\mathcal{L}^{(t-1)}| < \\epsilon \\quad \\text{or} \\quad \\|\\nabla \\mathcal{L}(w^{(t)})\\| < \\delta$$",
        "logic": "Monitoring training vs validation loss curves: Once validation loss stops improving for several epochs (patience), halting training prevents the model from memorizing noise.",
        "example": "Early stopping: Training stops automatically at Epoch 14 when validation loss fails to decrease for 3 consecutive epochs.",
        "tags": ["Convergence", "Loss Curve", "Early Stopping"]
    },
    {
        "id": "concept_lr_schedules",
        "title": "Learning Rate Schedules & Cosine Decay",
        "topic_id": "ml_opt",
        "topic_label": "Gradient Descent & Hyperparameters",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Learning Rate Schedules (Decay, Warmup, Cosine Annealing)",
        "def": "Predetermined policies that dynamically adjust the learning rate over the course of training (e.g. linear warmup followed by cosine annealing decay).",
        "formula": "$$\\eta_t = \\eta_{\\min} + \\frac{1}{2}(\\eta_{\\max} - \\eta_{\\min})\\left(1 + \\cos\\left(\\frac{t}{T}\\pi\\right)\\right)$$",
        "logic": "High initial learning rates help escape shallow local minima early on; gradually decaying the rate allows parameters to settle into the deepest, flattest optimal basins.",
        "example": "Transformer training (Llama): 2,000 steps of linear warmup from 0 to $3 \\times 10^{-4}$, followed by cosine decay down to $3 \\times 10^{-5}$ across 500,000 steps.",
        "tags": ["LR Schedulers", "Cosine Decay", "Warmup", "LLM Training"]
    },
    {
        "id": "concept_sigmoid",
        "title": "Sigmoid Activation Function",
        "topic_id": "ml_logistic",
        "topic_label": "Logistic Regression & Sigmoid",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Sigmoid Function (S-curve mapping to [0, 1])",
        "def": "A smooth mathematical S-curve function that maps any real-valued number from $-\\infty$ to $+\\infty$ strictly into a probability interval between 0 and 1.",
        "formula": "$$\\sigma(z) = \\frac{1}{1 + e^{-z}}, \\quad \\frac{d\\sigma}{dz} = \\sigma(z)(1 - \\sigma(z))$$",
        "logic": "Provides a clean probabilistic interpretation for binary classification. However, for large positive or negative inputs ($|z| > 5$), its derivative approaches zero, causing vanishing gradients in deep networks.",
        "example": "Credit fraud detector: Linear sum $z = w^T x + b = 2.19$ passes through $\\sigma(2.19) = \\frac{1}{1 + e^{-2.19}} = 0.90$, outputting a 90% probability of fraud.",
        "tags": ["Sigmoid", "Logistic Regression", "Probability Calibration"]
    },
    {
        "id": "concept_decision_threshold",
        "title": "Classification Decision Threshold",
        "topic_id": "ml_logistic",
        "topic_label": "Logistic Regression & Sigmoid",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Classification Threshold (Decision cutoff, default 0.5)",
        "def": "The value cutoff used to map a continuous probability prediction into a discrete binary class decision.",
        "formula": "$$\\hat{y} = \\begin{cases} 1 & \\text{if } P(Y=1|x) \\ge t \\\\ 0 & \\text{if } P(Y=1|x) < t \\end{cases}, \\quad t_{\\text{default}} = 0.5$$",
        "logic": "Google ML Crash Course Principle: 0.5 is almost never the optimal business threshold. In high-stakes applications (fraud, cancer), lowering the threshold to 0.1 maximizes Recall, catching all positive cases at the expense of more false alarms.",
        "example": "Spam filter vs Cancer detection: Spam filter uses threshold 0.95 (to ensure no important real email is accidentally sent to spam); cancer screening uses 0.05 (to ensure no tumor is overlooked).",
        "tags": ["Decision Threshold", "Classification", "Google MLCC"]
    },
    {
        "id": "concept_log_loss_classification",
        "title": "Log Loss Penalty in Classification",
        "topic_id": "ml_logistic",
        "topic_label": "Logistic Regression & Sigmoid",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Log Loss (Cross-Entropy penalty for incorrect confidence)",
        "def": "The convex loss formulation for logistic regression that penalizes false confidence with asymptotically infinite loss.",
        "formula": "$$\\text{Loss} = -\\left[ y \\ln(p) + (1 - y) \\ln(1 - p) \\right]$$",
        "logic": "Using MSE for logistic regression results in a non-convex loss surface with flat local plateaus. Log loss guarantees a strictly convex surface where any local minimum is the global optimum.",
        "example": "If the true label is 1 and the model predicts 0.99, loss is 0.01; if it predicts 0.0001, loss is 9.21, exerting a massive corrective gradient.",
        "tags": ["Log Loss", "Convexity", "Logistic Regression"]
    },
    {
        "id": "concept_logits_log_odds",
        "title": "Log-Odds & Logits",
        "topic_id": "ml_logistic",
        "topic_label": "Logistic Regression & Sigmoid",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Log-Odds & Logit Transformation: ln(p / (1-p))",
        "def": "The natural logarithm of the odds ratio $p / (1-p)$, representing the linear unconstrained output of a classification model before applying the sigmoid function.",
        "formula": "$$\\text{Logit}(p) = \\ln\\left(\\frac{p}{1 - p}\\right) = w^T x + b \\implies p = \\frac{1}{1 + e^{-(w^T x + b)}}$$",
        "logic": "Probabilities are strictly bounded in $[0, 1]$, making linear regression mathematically incompatible with probability outputs. The logit transformation maps $[0, 1]$ onto $(-\\infty, +\\infty)$, restoring linear modeling capability.",
        "example": "Odds of winning: If probability of winning is 0.8, the odds are $0.8 / 0.2 = 4:1$. The log-odds is $\\ln(4) \\approx 1.386$.",
        "tags": ["Logits", "Log-Odds", "Logistic Regression", "Mathematics"]
    },
    {
        "id": "concept_multiclass_softmax",
        "title": "Multiclass Softmax",
        "topic_id": "ml_logistic",
        "topic_label": "Logistic Regression & Sigmoid",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Multiclass Softmax (Normalizing scores into probability distribution)",
        "def": "The generalization of the logistic function to $K$ classes, converting a vector of arbitrary raw real-valued scores (logits) into a probability distribution where all entries sum to 1.",
        "formula": "$$P(Y = k \\mid z) = \\frac{e^{z_k}}{\\sum_{j=1}^K e^{z_j}}, \\quad \\sum_{k=1}^K P(Y=k) = 1.0$$",
        "logic": "Exponentiation ensures all probability outputs are strictly non-negative, and division by the sum enforces that the outputs form a valid probability simplex.",
        "example": "Classifying an animal image across [Cat, Dog, Bird]: Logits `[2.0, 1.0, 0.1]` exponentiate to `[7.39, 2.72, 1.11]` and normalize to `[66% Cat, 24% Dog, 10% Bird]`.",
        "tags": ["Softmax", "Multiclass", "Classification", "Logits"]
    },
    {
        "id": "concept_l2_ridge",
        "title": "L2 Regularization (Ridge Regression)",
        "topic_id": "ml_reg",
        "topic_label": "Regularization (L1 Lasso & L2 Ridge)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "L2 Regularization / Ridge (Penalizes squared weights)",
        "def": "A regularization method that adds a penalty proportional to the sum of squared weights ($\\frac{\\lambda}{2} \\sum w_j^2$) to the loss function, shrinking weights toward zero.",
        "formula": "$$\\min_w \\frac{1}{2n} \\|y - Xw\\|_2^2 + \\frac{\\lambda}{2} \\sum_{j=1}^d w_j^2, \\quad w^* = (X^T X + \\lambda I)^{-1} X^T y$$",
        "logic": "L2 penalties shrink large weights evenly across all collinear features, stabilizing matrix inversion $(X^T X + \\lambda I)$ and significantly reducing model variance.",
        "example": "Predicting house prices with 50 collinear census features: Without L2, weights oscillate between +10,000 and -10,000. With L2, weights shrink smoothly to moderate magnitudes like +15 and -12.",
        "tags": ["Ridge Regression", "L2 Regularization", "Weight Decay"]
    },
    {
        "id": "concept_l1_lasso",
        "title": "L1 Regularization (Lasso Regression)",
        "topic_id": "ml_reg",
        "topic_label": "Regularization (L1 Lasso & L2 Ridge)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "L1 Regularization / Lasso (Induces feature sparsity)",
        "def": "A regularization method that adds a penalty proportional to the sum of absolute weight values ($\\lambda \\sum |w_j|$), driving non-essential feature weights strictly to zero.",
        "formula": "$$\\min_w \\frac{1}{2n} \\|y - Xw\\|_2^2 + \\lambda \\sum_{j=1}^d |w_j|$$",
        "logic": "The geometric constraint boundary of L1 is a diamond with sharp vertices on the coordinate axes. Optimization loss contours contact these vertices first, setting unimportant feature weights exactly to 0 (automated feature selection).",
        "example": "Gene expression data: A dataset has 20,000 gene features for 200 patients. L1 Lasso zeros out 19,950 irrelevant genes, isolating the top 50 predictive biomarkers.",
        "tags": ["Lasso", "L1 Regularization", "Sparsity", "Feature Selection"]
    },
    {
        "id": "concept_lambda_tuning",
        "title": "Lambda (λ) Hyperparameter Tuning",
        "topic_id": "ml_reg",
        "topic_label": "Regularization (L1 Lasso & L2 Ridge)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Lambda (λ) Hyperparameter (Tuning penalty strength)",
        "def": "The regularization scalar coefficient balancing the trade-off between fitting training data and keeping model complexity low.",
        "formula": "$$\\text{Total Objective} = \\text{Loss}(\\mathcal{D}_{\\text{train}}) + \\lambda \\cdot \\Omega(w)$$",
        "logic": "If $\\lambda = 0$, the model unrolls to pure OLS with high risk of overfitting. If $\\lambda \\to \\infty$, all weights shrink to zero, causing severe underfitting.",
        "example": "Grid search over $\\lambda \\in [10^{-4}, 10^{-3}, 10^{-2}, 10^{-1}, 1, 10]$ identifies $\\lambda = 0.1$ as the minimum of the cross-validation error curve.",
        "tags": ["Lambda", "Regularization", "Hyperparameter Search"]
    },
    {
        "id": "concept_elasticnet",
        "title": "ElasticNet Regularization",
        "topic_id": "ml_reg",
        "topic_label": "Regularization (L1 Lasso & L2 Ridge)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "ElasticNet (Weighted balance of L1 and L2 penalties)",
        "def": "A hybrid regularizer combining both L1 (sparsity) and L2 (grouping effect) penalties linearly via a mixing hyperparameter $\\alpha$.",
        "formula": "$$\\min_w \\frac{1}{2n}\\|y - Xw\\|^2 + \\lambda \\left( \\alpha \\sum |w_j| + \\frac{1 - \\alpha}{2} \\sum w_j^2 \\right)$$",
        "logic": "Lasso struggles when features are strongly correlated (it randomly picks one and drops the rest). ElasticNet groups correlated features together (L2 effect) while still pruning out useless noise features (L1 effect).",
        "example": "Genomic disease prediction: Highly correlated gene clusters are preserved together while millions of uncorrelated background noise readings are driven to zero.",
        "tags": ["ElasticNet", "L1", "L2", "Regularization"]
    },
    {
        "id": "concept_early_stopping",
        "title": "Early Stopping Regularization",
        "topic_id": "ml_reg",
        "topic_label": "Regularization (L1 Lasso & L2 Ridge)",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Early Stopping (Halting training before validation error rises)",
        "def": "A regularization method that monitors validation set performance after every epoch and halts training as soon as validation loss begins to diverge.",
        "formula": "$$\\tau^* = \\arg\\min_t \\mathcal{L}_{\\text{val}}(w^{(t)}), \\quad w_{\\text{final}} = w^{(\\tau^*)}$$",
        "logic": "Bishop PRML Proof: Stopping gradient descent after $\\tau$ iterations is mathematically equivalent to L2 weight decay with $\\lambda \\approx 1 / (\\tau \\eta)$.",
        "example": "Training an XGBoost model with 1,000 trees: Early stopping with patience=10 halts training at Tree 142 when validation loss reaches its lowest point.",
        "tags": ["Early Stopping", "Overfitting Prevention", "Validation"]
    },
    {
        "id": "concept_decision_trees_splitting",
        "title": "Decision Trees & Splitting Criteria",
        "topic_id": "ml_trees",
        "topic_label": "Decision Trees, Random Forests & XGBoost",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Decision Trees (Splitting on Gini Impurity or Entropy)",
        "def": "A non-parametric supervised model that partitions feature space into axis-aligned rectangular regions using recursive binary splits that maximize purity.",
        "formula": "$$\\text{Gini} = 1 - \\sum_{k=1}^K p_k^2, \\quad \\Delta I = I_{\\text{parent}} - \\left( \\frac{N_L}{N} I_L + \\frac{N_R}{N} I_R \\right)$$",
        "logic": "Decision trees require zero feature scaling and natively handle numerical and categorical data. They recursively pick the feature $j$ and threshold $t$ yielding maximum reduction in impurity.",
        "example": "Loan approval tree: Root split tests `credit_score > 650`. If True, splits on `income > $50,000`. If False, immediately routes to 'Deny'.",
        "tags": ["Decision Trees", "Gini Impurity", "Information Gain"]
    },
    {
        "id": "concept_tree_pruning",
        "title": "Tree Pruning & Depth Limits",
        "topic_id": "ml_trees",
        "topic_label": "Decision Trees, Random Forests & XGBoost",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Tree Pruning & Max Depth (Preventing memorization)",
        "def": "Techniques that restrict tree complexity by setting maximum depth, requiring minimum samples per leaf, or pruning branches with cost-complexity pruning.",
        "formula": "$$R_\\alpha(T) = R(T) + \\alpha |T| \\quad (|T| = \\text{Number of terminal leaves})$$",
        "logic": "An unconstrained tree grows until every single leaf contains exactly 1 sample, achieving 0% training error but catastrophic generalization error (pure memorization of noise).",
        "example": "Setting `max_depth = 4` and `min_samples_leaf = 20` prevents a tree from creating isolated leaves to fit individual outlier records.",
        "tags": ["Pruning", "Max Depth", "Tree Regularization"]
    },
    {
        "id": "concept_random_forest_bagging",
        "title": "Random Forest & Bagging",
        "topic_id": "ml_trees",
        "topic_label": "Decision Trees, Random Forests & XGBoost",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Random Forest (Bagging + Feature Subspace Sampling)",
        "def": "An ensemble method that trains hundreds of deep, independent decision trees in parallel on bootstrap samples, additionally sampling a random subset of features at each split.",
        "formula": "$$\\hat{y} = \\frac{1}{B} \\sum_{b=1}^B T_b(x), \\quad \\text{Var}(\\bar{T}) = \\rho \\sigma^2 + \\frac{1-\\rho}{B}\\sigma^2$$",
        "logic": "Averaging uncorrelated trees drastically reduces model variance without increasing bias. Random feature selection decorrelates trees, preventing dominant features from dictating every tree's root split.",
        "example": "Predicting hospital readmission: 500 decision trees vote on whether a patient will be readmitted. The aggregated probability provides high explainability and immunity to individual tree noise.",
        "tags": ["Random Forest", "Bagging", "Ensemble Methods", "Variance Reduction"]
    },
    {
        "id": "concept_gbdt",
        "title": "Gradient Boosted Decision Trees (GBDT)",
        "topic_id": "ml_trees",
        "topic_label": "Decision Trees, Random Forests & XGBoost",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Gradient Boosted Decision Trees (GBDT)",
        "def": "An additive ensemble method where shallow decision trees are trained sequentially, with each new tree fitting the pseudo-residuals (negative gradient) of the previous ensemble.",
        "formula": "$$F_m(x) = F_{m-1}(x) + \\eta h_m(x), \\quad r_{im} = -\\left[ \\frac{\\partial L(y_i, F(x_i))}{\\partial F(x_i)} \\right]_{F = F_{m-1}}$$",
        "logic": "While Random Forest reduces variance via parallel bagging, GBDT reduces bias by sequentially correcting the specific errors made by prior trees.",
        "example": "Search ranking: Tree 1 makes a broad prediction; Tree 2 predicts where Tree 1 was off; Tree 3 corrects Tree 2's errors. Scaled by learning rate $\\eta=0.05$.",
        "tags": ["GBDT", "Boosting", "Ensembles", "Residual Fitting"]
    },
    {
        "id": "concept_xgboost_lightgbm",
        "title": "XGBoost, LightGBM & CatBoost",
        "topic_id": "ml_trees",
        "topic_label": "Decision Trees, Random Forests & XGBoost",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "XGBoost, LightGBM & CatBoost (High-performance gradient boosting)",
        "def": "Modern production gradient boosting libraries featuring second-order Taylor approximations, histogram-based binning, leaf-wise tree growth, and native categorical handling.",
        "formula": "$$\\text{Gain} = \\frac{1}{2} \\left[ \\frac{G_L^2}{H_L + \\lambda} + \\frac{G_R^2}{H_R + \\lambda} - \\frac{(G_L + G_R)^2}{H_L + H_R + \\lambda} \\right] - \\gamma$$",
        "logic": "The undisputed champions of tabular ML competitions. LightGBM groups features into 256 discrete histogram bins, replacing $O(N \\log N)$ continuous sorting with blazing $O(K)$ bin operations.",
        "example": "Kaggle competition winning pipeline: LightGBM training on 10,000,000 tabular transaction rows in 45 seconds using 8 CPU cores.",
        "tags": ["XGBoost", "LightGBM", "CatBoost", "Tabular Dominance"]
    },
    {
        "id": "concept_k_means",
        "title": "K-Means Clustering & Centroid Updates",
        "topic_id": "ml_unsupervised",
        "topic_label": "Unsupervised Learning & Clustering",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "K-Means Clustering (Centroid updates & Elbow method)",
        "def": "An iterative unsupervised clustering algorithm that partitions $N$ observations into $K$ clusters by alternating between assigning points to their nearest centroid and recomputing centroids.",
        "formula": "$$J = \\sum_{k=1}^K \\sum_{i \\in C_k} \\|x_i - \\mu_k\\|^2, \\quad \\mu_k = \\frac{1}{|C_k|} \\sum_{i \\in C_k} x_i$$",
        "logic": "Coordinate descent on inertia $J$. Always converges to a local minimum. Use K-Means++ initialization to space out initial seeds and avoid poor sub-optimal local traps.",
        "example": "Customer market segmentation: Segmenting 100,000 shoppers into $K=5$ distinct shopping behavior personas using annual spend and visit frequency.",
        "tags": ["K-Means", "Clustering", "Unsupervised Learning"]
    },
    {
        "id": "concept_hierarchical_clustering",
        "title": "Hierarchical Clustering & Dendrograms",
        "topic_id": "ml_unsupervised",
        "topic_label": "Unsupervised Learning & Clustering",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Hierarchical Clustering (Agglomerative tree dendrograms)",
        "def": "A bottom-up (agglomerative) clustering method that starts with each data point in its own cluster and iteratively merges the closest pair of clusters until all points form a single tree.",
        "formula": "$$d_{\\text{Ward}}(A, B) = \\frac{|A| |B|}{|A| + |B|} \\|\\mu_A - \\mu_B\\|^2$$",
        "logic": "Does not require specifying $K$ upfront. The resulting dendrogram tree can be cut at any desired height threshold to reveal fine-grained or coarse-grained clusters.",
        "example": "Phylogenetic biological tree: Clustering evolutionary DNA sequences of species into an ancestral lineage tree.",
        "tags": ["Hierarchical", "Dendrogram", "Agglomerative", "Clustering"]
    },
    {
        "id": "concept_dbscan",
        "title": "DBSCAN Density-Based Clustering",
        "topic_id": "ml_unsupervised",
        "topic_label": "Unsupervised Learning & Clustering",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "DBSCAN (Density-based spatial clustering for arbitrary shapes)",
        "def": "A density-based clustering algorithm that groups together points that are closely packed, marking points that lie alone in low-density regions as noise outliers.",
        "formula": "$$N_\\epsilon(p) = \\{q \\in D \\mid \\text{dist}(p, q) \\le \\epsilon\\}, \\quad |N_\\epsilon(p)| \\ge \\text{MinPts}$$",
        "logic": "Unlike K-Means (which can only find spherical convex blobs), DBSCAN can discover arbitrary complex shapes (concentric rings, crescent moons) and explicitly filters noise.",
        "example": "GPS taxi drop-off hotspots: Identifying concentrated nightlife pickup zones in a city while ignoring isolated random suburban drop-offs.",
        "tags": ["DBSCAN", "Density Clustering", "Outlier Filtering"]
    },
    {
        "id": "concept_pca",
        "title": "Principal Component Analysis (PCA)",
        "topic_id": "ml_unsupervised",
        "topic_label": "Unsupervised Learning & Clustering",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "Principal Component Analysis (PCA for dimensionality reduction)",
        "def": "An orthogonal linear transformation that projects data onto the directions of maximal variance (principal components), minimizing reconstruction error.",
        "formula": "$$\\Sigma = \\frac{1}{n} X^T X, \\quad \\Sigma v_i = \\lambda_i v_i, \\quad Z = X V_k$$",
        "logic": "Compresses high-dimensional data while eliminating multicollinearity. The first principal component captures the largest single axis of variance, the second captures the second largest orthogonal axis, and so on.",
        "example": "Compressing facial images (Eigenfaces): 10,000 raw image pixels are compressed down to 50 principal components while preserving 95% of facial identity variance.",
        "tags": ["PCA", "Dimensionality Reduction", "Eigenvalues", "Covariance"]
    },
    {
        "id": "concept_tsne_umap",
        "title": "t-SNE & UMAP Manifold Projections",
        "topic_id": "ml_unsupervised",
        "topic_label": "Unsupervised Learning & Clustering",
        "category": "ml",
        "category_label": "Classical Machine Learning",
        "raw_subtopic": "t-SNE & UMAP (High-dimensional manifold projection)",
        "def": "Non-linear dimensionality reduction algorithms that map complex high-dimensional datasets into 2D or 3D for visual inspection, preserving local neighborhood structures.",
        "formula": "$$p_{j|i} = \\frac{\\exp(-\\|x_i - x_j\\|^2 / 2\\sigma_i^2)}{\\sum_{k \\neq i} \\exp(-\\|x_i - x_k\\|^2 / 2\\sigma_i^2)}, \\quad q_{ij} = \\frac{(1 + \\|y_i - y_j\\|^2)^{-1}}{\\sum (1 + \\|y_k - y_l\\|^2)^{-1}}$$",
        "logic": "PCA only captures linear projections. t-SNE and UMAP preserve non-linear topological manifolds, keeping points that were close in 1536-dimensional embedding space close on a 2D screen.",
        "example": "Visualizing OpenAI text embeddings: Plotting 10,000 news articles on a 2D scatter plot, where politics, sports, and science naturally cluster into tight distinct islands.",
        "tags": ["t-SNE", "UMAP", "Manifold Learning", "Visualization"]
    }
]
