"""
Concepts Database: Mathematical Foundations (19 Concepts)
"""

MATH_CONCEPTS = [
    {
        "id": "concept_dot_product_cosine",
        "title": "Vectors, Dot Products & Cosine Similarity",
        "topic_id": "math_linalg",
        "topic_label": "Linear Algebra & Vector Spaces",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Vectors, Dot Products & Geometric Cosine Similarity",
        "def": "A vector is an ordered list of numbers representing a point or direction in multi-dimensional space. The dot product sums the products of corresponding elements, and cosine similarity measures the directional alignment between two vectors regardless of magnitude.",
        "formula": "$$u \\cdot v = \\sum_{i=1}^d u_i v_i = \\|u\\| \\|v\\| \\cos(\\theta), \\quad \\text{Cosine Similarity} = \\frac{u \\cdot v}{\\|u\\|_2 \\|v\\|_2} = \\frac{\\sum u_i v_i}{\\sqrt{\\sum u_i^2} \\sqrt{\\sum v_i^2}}$$",
        "logic": "When comparing high-dimensional embeddings (e.g., text, images), Euclidean distance is heavily sensitive to document length or feature magnitude. Cosine similarity normalizes length away, isolating pure semantic orientation.",
        "example": "Comparing search queries: Query vector for 'electric car' [0.9, 0.1, 0.8] and document vector for 'Tesla EV vehicle' [0.85, 0.05, 0.75] produce a cosine similarity of 0.998, indicating near-perfect topical alignment.",
        "tags": ["Vectors", "Linear Algebra", "Cosine Similarity", "Embeddings"]
    },
    {
        "id": "concept_matrix_mult_inverses",
        "title": "Matrix Multiplication, Transposition & Inverses",
        "topic_id": "math_linalg",
        "topic_label": "Linear Algebra & Vector Spaces",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Matrix Multiplication, Transposition & Inverses",
        "def": "A matrix is a 2D grid of numbers representing linear transformations or entire datasets. Matrix multiplication composes transformations, transposition flips rows and columns across the diagonal, and an inverse matrix undoes the transformation.",
        "formula": "$$C = A B \\implies C_{ij} = \\sum_{k=1}^p A_{ik} B_{kj}, \\quad (A B)^T = B^T A^T, \\quad A A^{-1} = A^{-1} A = I$$",
        "logic": "Every feedforward layer in a neural network is a matrix multiplication $y = W X + b$. Computing matrix inverses directly is $O(d^3)$ and numerically unstable; modern solvers use iterative decompositions (QR, Cholesky, LU).",
        "example": "Batch forward pass: If you pass a batch of 64 image feature vectors of size 512 through a weight matrix of size [512, 128], a single matrix multiplication computes all 64 hidden representations simultaneously in GPU SRAM.",
        "tags": ["Matrices", "Matrix Multiply", "Linear Algebra", "Forward Pass"]
    },
    {
        "id": "concept_eigenvalues_eigenvectors",
        "title": "Eigenvalues & Eigenvectors",
        "topic_id": "math_linalg",
        "topic_label": "Linear Algebra & Vector Spaces",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Eigenvalues & Eigenvectors (Directions of invariant stretch)",
        "def": "Eigenvectors are special non-zero vectors that do not rotate when transformed by a square matrix; they only stretch or shrink by a scalar factor called the eigenvalue.",
        "formula": "$$A v = \\lambda v, \\quad \\det(A - \\lambda I) = 0$$",
        "logic": "Eigenvectors reveal the fundamental internal axes of a dataset or physical system. In PCA, the eigenvectors of the data covariance matrix identify the orthogonal directions of maximum data spread and variance.",
        "example": "Google PageRank algorithm: The web is modeled as a massive transition matrix $M$. The steady-state importance of every webpage is the principal eigenvector corresponding to eigenvalue $\\lambda = 1$.",
        "tags": ["Eigenvalues", "Eigenvectors", "Spectral Theory", "PCA"]
    },
    {
        "id": "concept_svd",
        "title": "Singular Value Decomposition (SVD)",
        "topic_id": "math_linalg",
        "topic_label": "Linear Algebra & Vector Spaces",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Singular Value Decomposition (SVD for compression)",
        "def": "A fundamental matrix factorization theorem stating that any arbitrary real matrix can be factored into rotation, scaling, and second rotation matrices.",
        "formula": "$$A = U \\Sigma V^T, \\quad A \\approx U_k \\Sigma_k V_k^T = \\sum_{i=1}^k \\sigma_i u_i v_i^T$$",
        "logic": "Eckart-Young Theorem proves that truncated SVD provides the provably optimal rank-$k$ approximation of any matrix under the Frobenius norm, maximizing preserved information while compressing storage.",
        "example": "Netflix Prize collaborative filtering: A massive user-movie rating matrix [500,000 users × 20,000 movies] is decomposed via truncated SVD to rank 50, revealing latent movie genres and user taste archetypes.",
        "tags": ["SVD", "Matrix Factorization", "Dimensionality Reduction", "Recommender Systems"]
    },
    {
        "id": "concept_tensors",
        "title": "Tensors & Multidimensional Arrays",
        "topic_id": "math_linalg",
        "topic_label": "Linear Algebra & Vector Spaces",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Tensors (Multidimensional arrays for batches and images)",
        "def": "A generalized mathematical array of numbers spanning arbitrary dimensions (rank 0 = scalar, rank 1 = vector, rank 2 = matrix, rank 3+ = tensor).",
        "formula": "$$\\mathcal{T} \\in \\mathbb{R}^{B \\times S \\times D} \\quad (\\text{Batch} \\times \\text{Sequence Length} \\times \\text{Embedding Dimension})$$",
        "logic": "Deep learning models compute on contiguous multi-dimensional memory blocks. Tensor broadcasting allows operations across tensors of mismatched shapes without redundant memory allocations.",
        "example": "A mini-batch of video clips: Stored as a 5D tensor of shape `[Batch_Size=16, Frames=30, Channels=3, Height=224, Width=224]`.",
        "tags": ["Tensors", "PyTorch", "Array Programming", "Deep Learning Data"]
    },
    {
        "id": "concept_partial_derivatives",
        "title": "Partial Derivatives & Slopes",
        "topic_id": "math_calc",
        "topic_label": "Calculus & Optimization Dynamics",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Partial Derivatives & Univariate Slopes",
        "def": "The rate of change of a multivariable function with respect to one single variable while holding all other variables constant as fixed values.",
        "formula": "$$\\frac{\\partial f}{\\partial x_i} = \\lim_{h \\to 0} \\frac{f(x_1, \\dots, x_i + h, \\dots, x_d) - f(x_1, \\dots, x_i, \\dots, x_d)}{h}$$",
        "logic": "Neural networks possess millions or billions of parameters. Partial derivatives isolate the individual sensitivity of the total loss to small perturbations of each specific weight.",
        "example": "Predicting car price from house age and square footage: $\\frac{\\partial \\text{Price}}{\\partial \\text{SqFt}}$ tells you how much the price rises per extra square foot, keeping house age strictly fixed.",
        "tags": ["Calculus", "Derivatives", "Sensitivity", "Optimization"]
    },
    {
        "id": "concept_chain_rule",
        "title": "The Chain Rule of Calculus",
        "topic_id": "math_calc",
        "topic_label": "Calculus & Optimization Dynamics",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "The Chain Rule of Calculus (Nested functions f(g(x)))",
        "def": "The mathematical formula for computing the derivative of composite, nested functions by multiplying the derivatives of each intermediate sub-function.",
        "formula": "$$\\frac{d}{dx} [f(g(x))] = f'(g(x)) \\cdot g'(x), \\quad \\frac{\\partial z}{\\partial x} = \\sum_k \\frac{\\partial z}{\\partial u_k} \\frac{\\partial u_k}{\\partial x}$$",
        "logic": "The chain rule is the mathematical bedrock of backpropagation. A neural network is simply a chain of composite functions $y = f_L(f_{L-1}(\\dots f_1(x)))$; gradients propagate backward layer by layer via sequential chain rule multiplications.",
        "example": "If your speed affects fuel consumption ($d\\text{Fuel}/d\\text{Speed}$), and pedal pressure affects speed ($d\\text{Speed}/d\\text{Pedal}$), the chain rule gives the direct impact of pedal pressure on fuel usage ($d\\text{Fuel}/d\\text{Pedal}$).",
        "tags": ["Chain Rule", "Calculus", "Backpropagation", "Deep Learning Foundations"]
    },
    {
        "id": "concept_gradient_vector",
        "title": "Gradient Vector & Steepest Ascent",
        "topic_id": "math_calc",
        "topic_label": "Calculus & Optimization Dynamics",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Gradient Vector (Direction of steepest increase)",
        "def": "A multi-dimensional vector collecting all partial derivatives of a scalar function, pointing directly in the compass direction of greatest rate of increase.",
        "formula": "$$\\nabla f(w) = \\left[ \\frac{\\partial f}{\\partial w_1}, \\frac{\\partial f}{\\partial w_2}, \\dots, \\frac{\\partial f}{\\partial w_d} \\right]^T, \\quad w^{(t+1)} = w^{(t)} - \\eta \\nabla f(w^{(t)})$$",
        "logic": "Because the gradient vector points in the direction of steepest increase, stepping in the negative gradient direction ($-\\nabla f$) guarantees the fastest local decrease in loss.",
        "example": "Hiking on a foggy hill (Google ML Crash Course analogy): You cannot see the valley floor, so you feel the ground tilt under your boots and step in the exact opposite direction of the upward slope.",
        "tags": ["Gradient", "Gradient Descent", "Optimization", "Vector Calculus"]
    },
    {
        "id": "concept_hessian_matrix",
        "title": "Hessian Matrix & 2nd Order Curvature",
        "topic_id": "math_calc",
        "topic_label": "Calculus & Optimization Dynamics",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Hessian Matrix (2nd order curvature & saddle points)",
        "def": "The square matrix of second-order partial derivatives describing the local curvature and bending of a multi-variable loss surface.",
        "formula": "$$H_{ij} = \\frac{\\partial^2 f}{\\partial w_i \\partial w_j}, \\quad H = \\begin{bmatrix} \\frac{\\partial^2 f}{\\partial w_1^2} & \\cdots & \\frac{\\partial^2 f}{\\partial w_1 \\partial w_d} \\\\ \\vdots & \\ddots & \\vdots \\\\ \\frac{\\partial^2 f}{\\partial w_d \\partial w_1} & \\cdots & \\frac{\\partial^2 f}{\\partial w_d^2} \\end{bmatrix}$$",
        "logic": "First-order gradients only tell you slope; second-order Hessians tell you if the slope is getting steeper or flatter. If eigenvalues of $H$ have mixed positive and negative signs, the point is a saddle point rather than an extremum.",
        "example": "XGBoost optimization: Taylor series expansion of loss uses the first derivative $g_i$ (gradient) and second derivative $h_i$ (Hessian diagonal) to calculate the exact optimal leaf weight analytically.",
        "tags": ["Hessian", "Second Order", "Curvature", "Newton Method", "XGBoost"]
    },
    {
        "id": "concept_convex_optimization",
        "title": "Convex vs Non-Convex Loss Landscapes",
        "topic_id": "math_calc",
        "topic_label": "Calculus & Optimization Dynamics",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Convex vs Non-Convex Loss Landscapes",
        "def": "A function is convex if a line segment drawn between any two points on the graph never lies below the graph itself. A convex function has exactly one unique global minimum and zero sub-optimal local minima.",
        "formula": "$$f(\\alpha x + (1-\\alpha)y) \\le \\alpha f(x) + (1-\\alpha)f(y) \\quad \\forall \\alpha \\in [0, 1], \\quad H(x) \\succeq 0$$",
        "logic": "Linear Regression and Logistic Regression are convex (guaranteed global optimum with standard gradient descent). Deep Neural Networks are non-convex with countless saddle points, requiring momentum, adaptive learning rates, and overparameterization to escape plateaus.",
        "example": "Convex bowl: A marble dropped into a soup bowl always rolls to the exact center bottom. Non-convex mountain range: A marble can get stuck in countless small puddles and ravines.",
        "tags": ["Convexity", "Optimization", "Global Minimum", "Loss Landscapes"]
    },
    {
        "id": "concept_random_variables_variance",
        "title": "Random Variables, Expectation & Variance",
        "topic_id": "math_prob",
        "topic_label": "Probability & Statistical Inference",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Random Variables, Expectation (Mean μ) & Variance (σ²)",
        "def": "A random variable maps random real-world outcomes to numerical values. Expectation is the probability-weighted average (mean), and variance measures how widely values spread around that mean.",
        "formula": "$$\\mathbb{E}[X] = \\mu = \\sum x_i P(x_i), \\quad \\text{Var}(X) = \\sigma^2 = \\mathbb{E}[(X - \\mu)^2] = \\mathbb{E}[X^2] - (\\mathbb{E}[X])^2$$",
        "logic": "Machine learning models are function approximators trained over empirical samples drawn from an underlying random distribution. Optimizing loss is equivalent to minimizing expected risk $\\mathbb{E}[\\mathcal{L}(y, \\hat{y})]$.",
        "example": "Fair die roll: Values 1 through 6 each with probability 1/6. Expected value is $\\mu = 3.5$, and variance is $\\sigma^2 = 2.92$.",
        "tags": ["Probability", "Expectation", "Variance", "Statistics"]
    },
    {
        "id": "concept_prob_distributions",
        "title": "Distributions: Gaussian, Bernoulli & Poisson",
        "topic_id": "math_prob",
        "topic_label": "Probability & Statistical Inference",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Distributions: Gaussian (Bell Curve), Bernoulli, Poisson",
        "def": "Mathematical functions that specify the probabilities of occurrence of different possible outcomes in an experiment.",
        "formula": "$$\\text{Gaussian: } p(x) = \\frac{1}{\\sqrt{2\\pi\\sigma^2}} e^{-\\frac{(x-\\mu)^2}{2\\sigma^2}}, \\quad \\text{Bernoulli: } P(y) = p^y (1-p)^{1-y}$$",
        "logic": "Selecting loss functions depends on the assumed output distribution: Gaussian assumption leads to Mean Squared Error; Bernoulli assumption leads to Binary Cross-Entropy; Poisson assumption leads to Poisson deviance loss.",
        "example": "Bernoulli models whether an ad is clicked (0 or 1); Gaussian models the continuous price of a used house; Poisson models the number of website visits per minute.",
        "tags": ["Distributions", "Gaussian", "Bernoulli", "Loss Foundations"]
    },
    {
        "id": "concept_bayes_theorem",
        "title": "Bayes' Theorem: Prior, Likelihood & Posterior",
        "topic_id": "math_prob",
        "topic_label": "Probability & Statistical Inference",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Bayes' Theorem: Prior, Likelihood, Evidence & Posterior",
        "def": "A mathematical formula that describes how to update the probability of a hypothesis as new evidence or data is observed.",
        "formula": "$$P(\\theta | \\mathcal{D}) = \\frac{P(\\mathcal{D} | \\theta) \\cdot P(\\theta)}{P(\\mathcal{D})} = \\frac{\\text{Likelihood} \\times \\text{Prior}}{\\text{Evidence}}$$",
        "logic": "Provides a formal mechanism to integrate domain knowledge (the Prior) with real observed data (the Likelihood) to reach a statistically sound revised conclusion (the Posterior).",
        "example": "Spam filtering: If 20% of all emails are spam (Prior $P(S)=0.2$), and the word 'lottery' appears in 80% of spam but only 1% of ham, Bayes' theorem computes the revised probability that an incoming email with 'lottery' is spam as ~95.2%.",
        "tags": ["Bayes Rule", "Probability", "Inference", "Naive Bayes"]
    },
    {
        "id": "concept_mle_map",
        "title": "Maximum Likelihood (MLE) vs MAP Estimation",
        "topic_id": "math_prob",
        "topic_label": "Probability & Statistical Inference",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Maximum Likelihood Estimation (MLE) vs MAP Estimation",
        "def": "MLE finds parameters that maximize the probability of observed data without any priors. MAP finds parameters that maximize the posterior, incorporating prior beliefs.",
        "formula": "$$\\hat{\\theta}_{\\text{MLE}} = \\arg\\max_\\theta \\sum_{i=1}^n \\log P(x_i | \\theta), \\quad \\hat{\\theta}_{\\text{MAP}} = \\arg\\max_\\theta \\left[ \\sum_{i=1}^n \\log P(x_i | \\theta) + \\log P(\\theta) \\right]$$",
        "logic": "Ridge regression is mathematically identical to MAP estimation assuming a zero-mean Gaussian prior on weights; Lasso regression is MAP with a zero-mean Laplace prior on weights.",
        "example": "Coin flip: If you flip a coin 3 times and get 3 heads, MLE concludes $P(\\text{Heads}) = 1.0$ (ridiculous). MAP with a prior centered at 0.5 concludes $P(\\text{Heads}) \\approx 0.625$.",
        "tags": ["MLE", "MAP", "Bayesian", "Regularization Duality"]
    },
    {
        "id": "concept_clt_lln",
        "title": "Law of Large Numbers & Central Limit Theorem",
        "topic_id": "math_prob",
        "topic_label": "Probability & Statistical Inference",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Law of Large Numbers & Central Limit Theorem",
        "def": "The Law of Large Numbers (LLN) states that sample averages converge to expected values as sample size grows. The Central Limit Theorem (CLT) states that the sum or average of independent random variables approaches a normal distribution, regardless of the original distribution shape.",
        "formula": "$$\\lim_{n \\to \\infty} \\bar{X}_n = \\mu, \\quad \\sqrt{n}\\left(\\bar{X}_n - \\mu\\right) \\xrightarrow{d} \\mathcal{N}(0, \\sigma^2)$$",
        "logic": "Allows data scientists to compute confidence intervals and conduct valid hypothesis tests (e.g. A/B testing z-tests) on arbitrary metrics because sample means are guaranteed to be normally distributed.",
        "example": "Rolling 100 dice: Individual dice outcomes are uniform flat [1, 2, 3, 4, 5, 6]. But if you roll 100 dice and sum them, the resulting sum across thousands of trials forms an exquisite bell curve centered at 350.",
        "tags": ["CLT", "Statistics", "A/B Testing", "Confidence Intervals"]
    },
    {
        "id": "concept_shannon_entropy",
        "title": "Shannon Entropy",
        "topic_id": "math_info",
        "topic_label": "Information Theory & Cross-Entropy",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Shannon Entropy (Measure of inherent uncertainty)",
        "def": "The average amount of information, surprise, or uncertainty inherent in the possible outcomes of a random variable.",
        "formula": "$$H(X) = -\\sum_{i=1}^n P(x_i) \\log_2 P(x_i)$$",
        "logic": "A deterministic event with probability 1.0 contains 0 bits of information (0 entropy, no surprises). Maximum entropy occurs when all outcomes are equally likely (maximum unpredictability).",
        "example": "A fair coin has $H = -(0.5 \\log_2 0.5 + 0.5 \\log_2 0.5) = 1.0$ bit of entropy. A rigged coin that lands on heads 99% of the time has $H = 0.08$ bits (almost no surprise).",
        "tags": ["Entropy", "Information Theory", "Uncertainty", "Decision Trees"]
    },
    {
        "id": "concept_cross_entropy",
        "title": "Cross-Entropy Loss",
        "topic_id": "math_info",
        "topic_label": "Information Theory & Cross-Entropy",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Cross-Entropy Loss (Standard classification objective)",
        "def": "A loss metric quantifying the difference between two probability distributions: the true distribution $P$ and the predicted distribution $Q$.",
        "formula": "$$H(P, Q) = -\\sum_{x} P(x) \\log Q(x) = -\\sum_{k=1}^K y_k \\log(\\hat{y}_k)$$",
        "logic": "The loss approaches infinity as the model predicts zero probability for the correct true class. This creates steep, aggressive corrective gradients when a model is confidently wrong.",
        "example": "Dog vs Cat classifier: True label is Dog [1, 0]. If the model predicts Dog with probability 0.99, loss is $-\\log(0.99) = 0.01$. If it foolishly predicts Dog with probability 0.01, loss is $-\\log(0.01) = 4.60$.",
        "tags": ["Cross Entropy", "Loss Functions", "Classification", "Log Loss"]
    },
    {
        "id": "concept_kl_divergence",
        "title": "Kullback-Leibler (KL) Divergence",
        "topic_id": "math_info",
        "topic_label": "Information Theory & Cross-Entropy",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Kullback-Leibler (KL) Divergence (Distribution distance)",
        "def": "An asymmetric measure of the statistical distance or information lost when an approximating distribution $Q$ is used to represent a true distribution $P$.",
        "formula": "$$D_{\\text{KL}}(P \\parallel Q) = \\sum_{x} P(x) \\log\\left( \\frac{P(x)}{Q(x)} \\right) = H(P, Q) - H(P)$$",
        "logic": "Always non-negative ($D_{\\text{KL}} \\ge 0$) via Gibbs' inequality, and zero if and only if $P = Q$. Used in Variational Autoencoders (VAEs) and RLHF / DPO to prevent fine-tuned models from drifting too far from their base pre-trained models.",
        "example": "LLM Alignment: In RLHF, a KL-penalty term $-\\beta D_{\\text{KL}}(\\pi_\\theta \\parallel \\pi_{\\text{ref}})$ prevents the agent from hacking the reward model by deviating into gibberish.",
        "tags": ["KL Divergence", "Information Distance", "VAE", "RLHF Alignment"]
    },
    {
        "id": "concept_mutual_information",
        "title": "Mutual Information",
        "topic_id": "math_info",
        "topic_label": "Information Theory & Cross-Entropy",
        "category": "math",
        "category_label": "Mathematical Foundations",
        "raw_subtopic": "Mutual Information (Shared dependency between features)",
        "def": "A measure of the mutual dependence between two random variables; it quantifies how much knowing the value of one variable reduces uncertainty about the other.",
        "formula": "$$I(X; Y) = \\sum_{x, y} P(x, y) \\log\\left( \\frac{P(x, y)}{P(x) P(y)} \\right) = H(X) - H(X | Y)$$",
        "logic": "Unlike linear correlation (Pearson $r$) which only captures straight-line associations, Mutual Information captures arbitrary non-linear and non-monotonic relationships between features and labels.",
        "example": "Feature selection for credit default: A feature 'Age' and label 'Default' may have Pearson $r \\approx 0$ due to a U-shaped risk curve (very young and very old default more). Mutual Information easily captures this high predictive value.",
        "tags": ["Mutual Information", "Feature Selection", "Non-linear Dependence"]
    }
]
