"""
Generative AI & LLMs Core Concepts (32 concepts):
- Tokenization & Vector Embeddings
- Self-Attention & Transformer Core
- Pre-training, SFT & PEFT (LoRA/QLoRA)
- Alignment: RLHF, DPO & Distillation
- Retrieval-Augmented Generation (RAG)
- Prompt Engineering & Autonomous Agents
"""

GENAI_CONCEPTS = [
    # genai_embed
    {
        "id": "tokenizers-bpe-wordpiece-sentencepiece",
        "topic_id": "genai_embed",
        "topic_label": "Tokenization & Vector Embeddings",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Subword Tokenization (BPE, WordPiece, SentencePiece)",
        "raw_sub": "Tokenizers (Byte-Pair Encoding BPE, WordPiece, SentencePiece)",
        "definition": "Subword tokenization breaks arbitrary text into vocabulary chunks (subwords, characters, or byte sequences) balancing vocabulary size and sequence length, completely eliminating Out-Of-Vocabulary (OOV) tokens by merging frequent character pairs iteratively.",
        "formula": "$$\\text{Score}(u, v) = \\frac{\\text{freq}(u, v)}{\\text{freq}(u) \\times \\text{freq}(v)} \\quad \\text{or} \\quad \\text{argmax}_{u, v} \\; \\text{Count}(uv)$$",
        "formula_explanation": "BPE greedily merges the most frequent byte pair in each iteration until vocabulary size reaches target $V$ (e.g. 32k to 128k tokens).",
        "logic": "Character tokenization makes sequences too long for attention; whole-word tokenization causes vocabulary explosion and fails on novel words. Subword tokenization represents common words ('learning') as single tokens and rare words ('hyperparameter') as composite subwords ('hyper', 'parameter').",
        "example": "In GPT-4 (tiktoken `cl100k_base`): 'antigravity' is tokenized into two subwords: `['anti', 'gravity']`, preserving semantic morphology."
    },
    {
        "id": "dense-vector-embeddings",
        "topic_id": "genai_embed",
        "topic_label": "Tokenization & Vector Embeddings",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Dense Vector Embeddings & Semantic Geometry",
        "raw_sub": "Dense Vector Embeddings (Semantic clustering)",
        "definition": "Dense vector embeddings map discrete tokens, sentences, or documents into continuous real-valued geometric vector spaces $\\mathbb{R}^d$ where cosine similarity captures deep semantic and functional relatedness.",
        "formula": "$$\\text{sim}(\\mathbf{u}, \\mathbf{v}) = \\cos(\\theta) = \\frac{\\mathbf{u} \\cdot \\mathbf{v}}{\\|\\mathbf{u}\\|_2 \\|\\mathbf{v}\\|_2} = \\frac{\\sum_{i=1}^d u_i v_i}{\\sqrt{\\sum u_i^2}\\sqrt{\\sum v_i^2}}$$",
        "formula_explanation": "When vectors are L2-normalized ($\\|\\mathbf{u}\\|_2 = 1$), cosine similarity simplifies directly to the inner dot product $\\mathbf{u}^T \\mathbf{v}$.",
        "logic": "Embeddings solve the curse of one-hot sparsity. In embedding space, vector arithmetic exhibits semantic linearity: $\\mathbf{v}_{king} - \\mathbf{v}_{man} + \\mathbf{v}_{woman} \\approx \\mathbf{v}_{queen}$.",
        "example": "Text embeddings: 'cardiac arrest' and 'heart attack' share zero overlapping words, but their OpenAI `text-embedding-3-small` vectors have cosine similarity $> 0.92$."
    },
    {
        "id": "positional-encodings-rope",
        "topic_id": "genai_embed",
        "topic_label": "Tokenization & Vector Embeddings",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Positional Encodings & Rotary Embeddings (RoPE)",
        "raw_sub": "Positional Encodings (Sinusoidal & Rotary Position Embedding RoPE)",
        "definition": "Because self-attention is permutation-invariant (order-blind), positional encodings inject sequence order. Rotary Position Embedding (RoPE - Su et al., 2021) rotates 2D chunks of Query and Key vectors by angle $m\\theta$, encoding relative token distance naturally into dot products.",
        "formula": "$$\\mathbf{R}_{\\Theta, m}^d = \\text{diag}\\left( \\begin{bmatrix} \\cos m\\theta_i & -\\sin m\\theta_i \\\\ \\sin m\\theta_i & \\cos m\\theta_i \\end{bmatrix} \\right), \\quad (\\mathbf{R}_m \\mathbf{q})^T (\\mathbf{R}_n \\mathbf{k}) = \\mathbf{q}^T \\mathbf{R}_{n-m} \\mathbf{k}$$",
        "formula_explanation": "$m$ and $n$ are absolute token positions. The attention inner product depends strictly on relative offset $n-m$, decaying gracefully as tokens separate.",
        "logic": "Absolute sinusoidal embeddings (Vaswani 2017) degrade when extrapolating beyond training context. RoPE preserves relative distances and enables length scaling via frequency interpolation (YaRN, NTK-aware scaling).",
        "example": "Used in LLaMA-3, Mistral, and Claude: RoPE allows models trained on 8k tokens to extend gracefully to 128k+ tokens through NTK frequency scaling."
    },
    {
        "id": "collaborative-filtering-embeddings",
        "topic_id": "genai_embed",
        "topic_label": "Tokenization & Vector Embeddings",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Collaborative Filtering via Matrix Factorization Embeddings",
        "raw_sub": "Collaborative Filtering via Matrix Factorization Embeddings",
        "definition": "Matrix factorization decomposes a sparse user-item interaction matrix $\\mathbf{R}$ into dense low-rank user embedding matrix $\\mathbf{U}$ and item embedding matrix $\\mathbf{V}$, capturing latent preferences and attributes for personalized recommendations.",
        "formula": "$$\\min_{\\mathbf{U}, \\mathbf{V}} \\sum_{(u, i) \\in \\Omega} (r_{ui} - \\mathbf{u}_u^T \\mathbf{v}_i)^2 + \\lambda (\\|\\mathbf{u}_u\\|_2^2 + \\|\\mathbf{v}_i\\|_2^2)$$",
        "formula_explanation": "$r_{ui}$ is the observed rating/click, $\\mathbf{u}_u \\in \\mathbb{R}^k$ is user $u$'s embedding, $\\mathbf{v}_i \\in \\mathbb{R}^k$ is item $i$'s embedding, and $\\lambda$ prevents overfitting.",
        "logic": "Users with similar viewing histories end up nearby in latent space. When user $A$ likes movies $X, Y$ and user $B$ likes $X, Y, Z$, user $A$'s dot product with movie $Z$ will be high, generating the recommendation.",
        "example": "Netflix / YouTube recommender systems: factorizing hundreds of millions of user watch records into 128-dimensional embedding vectors for instantaneous candidate retrieval."
    },
    {
        "id": "context-windows-extrapolation",
        "topic_id": "genai_embed",
        "topic_label": "Tokenization & Vector Embeddings",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Context Windows & Sequence Length Extrapolation",
        "raw_sub": "Context Windows & Sequence Length Extrapolation",
        "definition": "Context window defines the maximum sequence length an LLM can consume in a single forward pass. Extrapolation techniques (ALiBi, RoPE interpolation, LongLoRA) allow models pre-trained on short sequences to process 100k to 1M+ tokens without catastrophic perplexity explosion.",
        "formula": "$$\\text{Attention}_{ALiBi} = \\text{Softmax}\\left( \\frac{\\mathbf{Q}\\mathbf{K}^T}{\\sqrt{d_k}} - m \\cdot |i - j| \\right)$$",
        "formula_explanation": "ALiBi (Press et al., 2021) subtracts a linear penalty proportional to token distance $|i-j|$, with head-specific constant slope $m$.",
        "logic": "Standard self-attention memory scales quadratically $O(N^2)$ with token length $N$. RingAttention and Chunked FlashAttention distribute long context across GPU clusters to make 1-million-token prompts feasible.",
        "example": "Uploading a 500-page financial PDF into Gemini 1.5 Pro (2-million token context window) and asking targeted compliance questions across historical disclosures."
    },

    # genai_attention
    {
        "id": "query-key-value-projections",
        "topic_id": "genai_attention",
        "topic_label": "Self-Attention & Transformer Core",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Query (Q), Key (K), and Value (V) Projections",
        "raw_sub": "Query (Q), Key (K), and Value (V) Vector Projections",
        "definition": "Self-attention transforms each input token embedding $\\mathbf{x}$ into three distinct functional vector roles through learned linear projection weight matrices: Query $\\mathbf{Q}$ (what I am looking for), Key $\\mathbf{K}$ (what I contain), and Value $\\mathbf{V}$ (the actual content payload).",
        "formula": "$$\\mathbf{Q} = \\mathbf{X} \\mathbf{W}_Q, \\quad \\mathbf{K} = \\mathbf{X} \\mathbf{W}_K, \\quad \\mathbf{V} = \\mathbf{X} \\mathbf{W}_V$$",
        "formula_explanation": "For input sequence $\\mathbf{X} \\in \\mathbb{R}^{N \\times d_{model}}$, weight matrices $\\mathbf{W}_Q, \\mathbf{W}_K, \\mathbf{W}_V \\in \\mathbb{R}^{d_{model} \\times d_k}$ generate representations $\\mathbf{Q}, \\mathbf{K}, \\mathbf{V} \\in \\mathbb{R}^{N \\times d_k}$.",
        "logic": "Decoupling Key and Value is the core innovation: the Key is optimized for indexing and matching against Queries, while the Value stores the raw semantic information transferred upon a match.",
        "example": "In a database search analogy: a search query string is $\\mathbf{Q}$, column index titles are $\\mathbf{K}$, and row table contents returned are $\\mathbf{V}$."
    },
    {
        "id": "scaled-dot-product-attention",
        "topic_id": "genai_attention",
        "topic_label": "Self-Attention & Transformer Core",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Scaled Dot-Product Attention",
        "raw_sub": "Scaled Dot-Product Attention & Temperature Scaling (√d_k)",
        "definition": "Scaled Dot-Product Attention (Vaswani et al., 2017) computes token relevance weights by taking dot products between queries and keys, dividing by $\\sqrt{d_k}$ to prevent variance explosion, applying softmax, and computing a weighted sum of values.",
        "formula": "$$\\text{Attention}(\\mathbf{Q}, \\mathbf{K}, \\mathbf{V}) = \\text{Softmax}\\left( \\frac{\\mathbf{Q}\\mathbf{K}^T}{\\sqrt{d_k}} \\right) \\mathbf{V}$$",
        "formula_explanation": "$d_k$ is the dimensionality of query/key vectors. If components have zero mean and unit variance, the dot product $\\mathbf{q} \\cdot \\mathbf{k}$ has variance $d_k$; dividing by $\\sqrt{d_k}$ restores unit variance.",
        "logic": "Without the scaling factor $\\sqrt{d_k}$, large dimensions (e.g. $d_k = 128$) produce huge dot products, pushing Softmax into regions with near-zero gradients (vanishing gradient saturation).",
        "example": "With $d_k=64$, $\\sqrt{d_k}=8$. If $\\mathbf{q} \\cdot \\mathbf{k} = 32.0$, scaling rescales it to $4.0$, keeping Softmax gradients alive and informative."
    },
    {
        "id": "multi-head-attention-mha",
        "topic_id": "genai_attention",
        "topic_label": "Self-Attention & Transformer Core",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Multi-Head Attention (MHA)",
        "raw_sub": "Multi-Head Attention (MHA for diverse linguistic perspectives)",
        "definition": "Multi-Head Attention projects Queries, Keys, and Values into $h$ separate representation subspaces in parallel, allowing the model to attend simultaneously to information from different representation positions and semantic perspectives.",
        "formula": "$$\\text{MHA}(\\mathbf{Q}, \\mathbf{K}, \\mathbf{V}) = [\\text{head}_1; \\dots; \\text{head}_h]\\mathbf{W}_O, \\quad \\text{head}_i = \\text{Attention}(\\mathbf{Q}\\mathbf{W}_i^Q, \\mathbf{K}\\mathbf{W}_i^K, \\mathbf{V}\\mathbf{W}_i^V)$$",
        "formula_explanation": "$h$ is number of heads (typically 32 to 128), head dimension is $d_k = \\frac{d_{model}}{h}$, and $\\mathbf{W}_O \\in \\mathbb{R}^{d_{model} \\times d_{model}}$ fuses head outputs.",
        "logic": "A single attention head can only focus on one type of relationship (e.g. grammatical subject). Multiple heads allow one head to track syntax, another to resolve pronoun coreference, and another to capture semantic tone.",
        "example": "In 'The dog didn't cross the street because *it* was too tired': Head 3 links 'it' to 'dog', while Head 7 links 'cross' to 'street'."
    },
    {
        "id": "grouped-query-attention-gqa",
        "topic_id": "genai_attention",
        "topic_label": "Self-Attention & Transformer Core",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Grouped-Query Attention (GQA)",
        "raw_sub": "Grouped-Query Attention (GQA to compress KV-cache memory)",
        "definition": "Grouped-Query Attention (Ainslie et al., 2023) interpolates between Multi-Head Attention (MHA) and Multi-Query Attention (MQA) by sharing single Key and Value heads across groups of Query heads, dramatically compressing KV-cache memory during autoregressive inference.",
        "formula": "$$G = \\frac{H_Q}{H_{KV}} \\quad (\\text{e.g. } H_Q = 32, H_{KV} = 8 \\implies G = 4)$$",
        "formula_explanation": "$H_Q$ is query heads, $H_{KV}$ is key-value heads. Each group of $G$ query heads attends to the identical shared KV projection.",
        "logic": "During LLM generation, caching Keys and Values dominates GPU high-bandwidth memory (HBM). GQA with $G=8$ reduces KV-cache memory bandwidth by $8\\times$ with negligible quality loss.",
        "example": "LLaMA-3 70B and Mistral 7B utilize GQA with 8 KV heads: enables serving $8\\times$ larger concurrent user batch sizes on a single GPU without running out of VRAM."
    },
    {
        "id": "causal-masking",
        "topic_id": "genai_attention",
        "topic_label": "Self-Attention & Transformer Core",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Causal Masking (Autoregressive Attention)",
        "raw_sub": "Causal Masking (Preventing future token visibility in autoregression)",
        "definition": "Causal masking enforces the arrow of time in decoder-only autoregressive LLMs by setting the upper triangular elements of the pre-softmax attention score matrix to $-\\infty$, preventing token $t$ from looking ahead to tokens at $t+1, t+2, \\dots$.",
        "formula": "$$\\mathbf{M}_{ij} = \\begin{cases} 0 & \\text{if } i \\ge j \\\\ -\\infty & \\text{if } i < j \\end{cases}, \\quad \\mathbf{S}_{masked} = \\text{Softmax}\\left( \\frac{\\mathbf{Q}\\mathbf{K}^T}{\\sqrt{d_k}} + \\mathbf{M} \\right)$$",
        "formula_explanation": "Because $e^{-\\infty} = 0$, applying Softmax assigns exactly 0% attention probability to all future token positions.",
        "logic": "Causal masking allows training on an entire prompt-and-response sequence of length $N$ in parallel during a single matrix multiplication pass, while strictly emulating step-by-step autoregressive generation.",
        "example": "When predicting word 4 in 'The cat sat on [?]', causal masking ensures the network only attends to tokens 1, 2, and 3, preventing data leakage."
    },

    # genai_train
    {
        "id": "self-supervised-pre-training",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Self-Supervised Pre-training (Causal LM)",
        "raw_sub": "Self-Supervised Pre-training (Next Token Prediction / Causal LM)",
        "definition": "Self-supervised pre-training trains a massive base neural network on trillions of tokens of raw internet text using Next-Token Prediction (Causal Language Modeling), forcing the model to absorb world knowledge, logic, and grammar without human labels.",
        "formula": "$$\\mathcal{L}_{CLM}(\\theta) = -\\sum_{t=1}^{T} \\log P_\\theta(x_t \\mid x_1, x_2, \\dots, x_{t-1})$$",
        "formula_explanation": "$x_t$ is the target token at position $t$ from the vocabulary, and $P_\\theta$ is the predicted probability assigned to that token given preceding context.",
        "logic": "Language is a compression of human intelligence. In order to accurately predict the next word across millions of science textbooks, code repositories, and philosophical treatises, the model must build internal world simulators.",
        "example": "Pre-training LLaMA-3: consuming 15 trillion tokens across 16,384 H100 GPUs over several months, resulting in an encyclopedic foundation model."
    },
    {
        "id": "supervised-fine-tuning-sft",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Supervised Fine-Tuning (SFT / Instruction Tuning)",
        "raw_sub": "Supervised Fine-Tuning (SFT on question-answer instructions)",
        "definition": "Supervised Fine-Tuning (SFT) transforms a raw autocomplete base model into an interactive conversational assistant by training on curated high-quality pairs of user prompts (instructions) and target assistant responses.",
        "formula": "$$\\mathcal{L}_{SFT}(\\theta) = -\\sum_{t=L_{prompt}+1}^{L_{total}} \\log P_\\theta(y_t \\mid \\mathbf{x}_{prompt}, y_1, \\dots, y_{t-1})$$",
        "formula_explanation": "Loss is computed strictly on response tokens ($t > L_{prompt}$); prompt tokens are masked out so the model is only penalized for response quality.",
        "logic": "The 'Superficial Alignment Hypothesis' (LIMA paper): almost all knowledge is learned during pre-training; SFT merely teaches the model the formatting style and conversational tone to surface that knowledge.",
        "example": "Prompt: 'Write a Python script to scrape an RSS feed.' Target response: 'Here is how you can use feedparser...'. Loss guides weights to produce helpful assistant behavior."
    },
    {
        "id": "parameter-efficient-fine-tuning-peft",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Parameter-Efficient Fine-Tuning (PEFT)",
        "raw_sub": "Parameter-Efficient Fine-Tuning (PEFT)",
        "definition": "PEFT freezes the overwhelming majority (99%+) of pre-trained LLM weights and only trains a tiny set of auxiliary parameters (e.g. adapter layers, prompt tuning tokens, or low-rank matrices), reducing memory requirements by orders of magnitude.",
        "formula": "$$\\boldsymbol{\\theta}_{total} = \\boldsymbol{\\theta}_{frozen} \\cup \\boldsymbol{\\phi}_{trainable}, \\quad |\\boldsymbol{\\phi}| \\ll |\\boldsymbol{\\theta}| \\quad (\\text{often } |\\boldsymbol{\\phi}| < 0.1\\% \\cdot |\\boldsymbol{\\theta}|)$$",
        "formula_explanation": "Gradients and optimizer states (which take $12-16$ bytes per parameter in Adam) are only stored for $\\boldsymbol{\\phi}$.",
        "logic": "Full fine-tuning of a 70B model requires ~1,100 GB of VRAM across multiple 80GB GPUs. PEFT allows fine-tuning that same 70B model on a single 48GB GPU by updating only 50M parameters.",
        "example": "Prefix Tuning, Adapters, and LoRA: training domain-specific adaptations for medical radiology reports without altering the base model."
    },
    {
        "id": "lora-low-rank-adaptation",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "LoRA (Low-Rank Adaptation)",
        "raw_sub": "LoRA (Low-Rank Adaptation with rank r decomposition)",
        "definition": "LoRA (Hu et al., 2021) freezes pre-trained weight matrix $\\mathbf{W}_0 \\in \\mathbb{R}^{d \\times k}$ and parameterizes its weight update delta $\\Delta \\mathbf{W}$ as the product of two low-rank matrices $\\mathbf{B} \\in \\mathbb{R}^{d \\times r}$ and $\\mathbf{A} \\in \\mathbb{R}^{r \\times k}$, where rank $r \\ll \\min(d, k)$.",
        "formula": "$$\\mathbf{h} = \\mathbf{W}_0 \\mathbf{x} + \\frac{\\alpha}{r} \\mathbf{B}\\mathbf{A}\\mathbf{x}, \\quad \\mathbf{A} \\sim \\mathcal{N}\\left(0, \\frac{1}{r}\\right), \\quad \\mathbf{B} = 0$$",
        "formula_explanation": "$r$ is low rank (e.g. 8 or 16). $\\mathbf{B}$ initialized to 0 ensures $\\Delta \\mathbf{W} = 0$ at step 0. $\\alpha$ is a constant scaling hyperparameter.",
        "logic": "The intrinsic rank of weight deltas during downstream fine-tuning is extremely small. Factorizing into rank 16 matrices reduces trainable parameters by $10,000\\times$. At inference, $\\Delta \\mathbf{W}$ can be permanently folded back into $\\mathbf{W}_0$ with zero added latency.",
        "example": "Fine-tuning a $4096 \\times 4096$ projection ($16.7$M parameters): rank $r=8$ decomposition requires only $(4096 \\times 8) + (8 \\times 4096) = 65,536$ parameters ($0.39\\%$ of original)."
    },
    {
        "id": "qlora-quantized-lora",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "QLoRA (Quantized Low-Rank Adaptation)",
        "raw_sub": "QLoRA (4-bit NormalFloat quantization + Paged Optimizers)",
        "definition": "QLoRA (Dettmers et al., 2023) quantizes the frozen base model to 4-bit NormalFloat (NF4), backpropagates gradients through the 4-bit weights into 16-bit LoRA adapters, and uses Paged Optimizers to manage memory spikes.",
        "formula": "$$\\mathbf{W}^{NF4} = \\text{Quantize}_{NF4}(\\mathbf{W}_0), \\quad \\mathbf{h} = \\text{Dequantize}_{FP16}(\\mathbf{W}^{NF4}) \\mathbf{x} + \\frac{\\alpha}{r}\\mathbf{BAx}$$",
        "formula_explanation": "NF4 is an information-theoretically optimal quantile quantization for normally distributed neural network weights.",
        "logic": "Base model weights are held in 4-bit memory (compressing a 65B model from 130GB down to under 35GB), and only unquantized high-precision LoRA adapters are updated.",
        "example": "Fine-tuning a 65-billion parameter model on a single consumer NVIDIA RTX 3090/4090 GPU (24GB VRAM) over a weekend."
    },
    {
        "id": "catastrophic-forgetting",
        "topic_id": "genai_train",
        "topic_label": "Pre-training, SFT & PEFT (LoRA/QLoRA)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Catastrophic Forgetting Mitigation",
        "raw_sub": "Catastrophic Forgetting Mitigation",
        "definition": "Catastrophic forgetting occurs when fine-tuning an LLM on a narrow new domain (e.g. legal text) causes it to abruptly lose pre-trained general reasoning, coding, or mathematical competencies learned during pre-training.",
        "formula": "$$\\mathcal{L}_{total} = \\mathcal{L}_{new\\_task} + \\gamma \\mathcal{L}_{pretrain\\_replay} + \\lambda \\sum_i F_i (\\theta_i - \\theta_i^*)^2$$",
        "formula_explanation": "Mitigated using Experience Replay (mixing 5-10% general pre-training data into fine-tuning) or Elastic Weight Consolidation (EWC) penalizing changes to critical parameters weighted by Fisher Information $F_i$.",
        "logic": "Fine-tuning updates weights along the gradient of the new task without constraint, inadvertently destroying delicate high-dimensional manifolds representing general reasoning.",
        "example": "Fine-tuning a coding model on Python: without mixing in math and conversational replay data, its ability to solve GSM8K math reasoning drops by 40%."
    },

    # genai_align
    {
        "id": "rlhf-reinforcement-learning-human-feedback",
        "topic_id": "genai_align",
        "topic_label": "Alignment: RLHF, DPO & Distillation",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "RLHF (Reinforcement Learning from Human Feedback)",
        "raw_sub": "RLHF (Reinforcement Learning from Human Feedback via PPO)",
        "definition": "RLHF aligns language model outputs with human intent (Helpful, Honest, Harmless) by training a Reward Model $r_\\psi(x, y)$ on human preference comparisons, then optimizing the LLM policy $\\pi_\\theta$ via Proximal Policy Optimization (PPO).",
        "formula": "$$\\max_{\\theta} \\mathbb{E}_{(x, y) \\sim \\mathcal{D}_{\\pi_\\theta}} [r_\\psi(x, y)] - \\beta D_{KL}(\\pi_\\theta(y|x) \\parallel \\pi_{ref}(y|x))$$",
        "formula_explanation": "$r_\\psi(x, y)$ is the scalar reward score, and the KL divergence penalty $\\beta D_{KL}$ prevents the model policy $\\pi_\\theta$ from straying too far from original base policy $\\pi_{ref}$ (reward hacking).",
        "logic": "Human evaluation of quality is easy to judge comparatively ($y_1 > y_2$) but hard to write an explicit calculus loss function for. RLHF bridges human intuitive preference into gradient optimization.",
        "example": "Turning InstructGPT and ChatGPT from toxic or rambly text completers into polite, well-structured, safe conversational assistants."
    },
    {
        "id": "dpo-direct-preference-optimization",
        "topic_id": "genai_align",
        "topic_label": "Alignment: RLHF, DPO & Distillation",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "DPO (Direct Preference Optimization)",
        "raw_sub": "DPO (Direct Preference Optimization on paired responses)",
        "definition": "DPO (Rafailov et al., 2023) mathematically proves that the constrained RLHF objective can be solved exactly via an implicit reward function, eliminating the need to train a separate reward model or run unstable PPO reinforcement learning loops.",
        "formula": "$$\\mathcal{L}_{DPO}(\\theta) = -\\mathbb{E}_{(x, y_w, y_l)} \\left[ \\log \\sigma \\left( \\beta \\log \\frac{\\pi_\\theta(y_w|x)}{\\pi_{ref}(y_w|x)} - \\beta \\log \\frac{\\pi_\\theta(y_l|x)}{\\pi_{ref}(y_l|x)} \\right) \\right]$$",
        "formula_explanation": "$y_w$ is the human-preferred 'winning' answer, $y_l$ is the 'losing' rejected answer, and $\\beta$ controls KL regularization strength.",
        "logic": "DPO reduces alignment to a simple binary cross-entropy classification loss directly over pairs of responses, providing immense mathematical stability and reducing GPU compute requirements by 3-5x compared to PPO.",
        "example": "Used to align modern open models like Zephyr-7B, Starling-LM, and LLaMA-3 Instruct directly on paired preference datasets."
    },
    {
        "id": "constitutional-ai-rlbif",
        "topic_id": "genai_align",
        "topic_label": "Alignment: RLHF, DPO & Distillation",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Constitutional AI & RLAIF",
        "raw_sub": "Constitutional AI & Automated Self-Correction",
        "definition": "Constitutional AI (Anthropic, Bai et al., 2022) replaces expensive human feedback with Reinforcement Learning from AI Feedback (RLAIF), using a written set of natural-language principles ('a constitution') to have the model critique and revise its own responses.",
        "formula": "$$\\text{Step 1: Critique: } c \\sim \\text{LLM}(x, y, \\text{Principle}) \\quad \\to \\quad \\text{Step 2: Revision: } y^* \\sim \\text{LLM}(x, y, c)$$",
        "formula_explanation": "Principles enforce rules like 'Choose the response that is less harmful and avoids assisting dangerous activities.'",
        "logic": "Human annotators are slow, expensive, and introduce personal biases. Constitutional AI allows alignment to scale transparently, with explicit public governance rules governing behavior.",
        "example": "Powering Claude 3: constitutional principles instruct the model to politely decline producing malware while remaining maximally helpful for cybersecurity defense analysis."
    },
    {
        "id": "knowledge-distillation",
        "topic_id": "genai_align",
        "topic_label": "Alignment: RLHF, DPO & Distillation",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Knowledge Distillation (Teacher-Student)",
        "raw_sub": "Knowledge Distillation (Teacher model soft labels train student)",
        "definition": "Knowledge distillation (Hinton et al., 2015) transfers the reasoning capacity of a massive teacher model (e.g. 405B) into a compact, lightweight student model (e.g. 8B) by training the student to match the teacher's softened output probability distribution.",
        "formula": "$$\\mathcal{L}_{KD} = (1 - \\alpha) \\mathcal{L}_{CE}(y, \\sigma(\\mathbf{z}_s)) + \\alpha T^2 \\cdot D_{KL}\\left( \\sigma\\left(\\frac{\\mathbf{z}_t}{T}\\right) \\,\\parallel\\, \\sigma\\left(\\frac{\\mathbf{z}_s}{T}\\right) \\right)$$",
        "formula_explanation": "$\\mathbf{z}_t$ and $\\mathbf{z}_s$ are teacher and student logits, $T$ is softmax temperature smoothing probabilities, and $\\alpha$ balances ground truth vs teacher alignment.",
        "logic": "The teacher's 'dark knowledge' (secondary probabilities over incorrect tokens, e.g. knowing a cat is closer to a tiger than a car) provides immensely richer learning signals than hard 0/1 labels.",
        "example": "DistilBERT (60% size of BERT, retains 97% performance) and LLaMA-3.1 8B fine-tuned using synthetic outputs generated by LLaMA-3.1 405B."
    },
    {
        "id": "model-quantization-awq-gptq-gguf",
        "topic_id": "genai_align",
        "topic_label": "Alignment: RLHF, DPO & Distillation",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Model Quantization (AWQ, GPTQ, GGUF)",
        "raw_sub": "Model Quantization (FP16 -> INT8 / INT4 via AWQ, GPTQ, GGUF)",
        "definition": "Quantization compresses model parameter weights from 16-bit floating point (FP16/BF16) down to 8-bit or 4-bit integers (INT8/INT4), slashing GPU memory footprint by $4\\times$ and accelerating memory-bound autoregressive decoding throughput.",
        "formula": "$$X_{int} = \\text{clamp}\\left(\\left\\lfloor \\frac{X_{fp}}{S} \\right\\rceil + Z, -2^{b-1}, 2^{b-1}-1\\right), \\quad S = \\frac{X_{max} - X_{min}}{2^b - 1}$$",
        "formula_explanation": "$S$ is the FP16 scale factor and $Z$ is zero-point integer offset. AWQ (Activation-aware Weight Quantization) protects the 1% most salient weight channels based on activation magnitudes.",
        "logic": "Autoregressive generation is memory-bandwidth bound, not compute bound. Fetching 4-bit weights from VRAM to compute cores takes $25\\%$ of the time compared to 16-bit weights.",
        "example": "Running LLaMA-3 8B: in FP16 it requires 16GB VRAM; quantized via GGUF (Q4_K_M) it requires only 4.8GB RAM, running comfortably on a MacBook or iPhone."
    },

    # genai_rag
    {
        "id": "document-parsing-chunking",
        "topic_id": "genai_rag",
        "topic_label": "Retrieval-Augmented Generation (RAG)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Document Parsing & Chunking Strategies",
        "raw_sub": "Document Parsing & Chunking (Fixed-size, Recursive, Semantic)",
        "definition": "Chunking breaks large documents into optimal discrete segments for vector retrieval. Strategies include Fixed-Size Chunking (character count with overlap), Recursive Character Splitting (respecting paragraphs and code fences), and Semantic Chunking (splitting when semantic embedding similarity shifts).",
        "formula": "$$\\text{Overlap Ratio} = \\frac{N_{overlap}}{N_{chunksize}} \\quad (\\text{typically } 10\\% - 20\\%)$$",
        "formula_explanation": "Sliding window overlap ensures sentences cut in half at chunk boundaries retain full semantic context in at least one chunk.",
        "logic": "If chunks are too small (e.g. 50 tokens), they lack sufficient surrounding context. If chunks are too large (e.g. 4000 tokens), specific factual details are diluted across general narrative in embedding space.",
        "example": "In LangChain / LlamaIndex: `RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200, separators=['\\n\\n', '\\n', ' ', ''])` keeps headers and paragraphs intact."
    },
    {
        "id": "vector-databases-indexing",
        "topic_id": "genai_rag",
        "topic_label": "Retrieval-Augmented Generation (RAG)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Vector Databases & Approximate Nearest Neighbor (ANN)",
        "raw_sub": "Vector Databases (Chroma, Pinecone, Milvus, Qdrant, FAISS)",
        "definition": "Vector databases store, index, and query multi-dimensional dense embeddings at scale using Approximate Nearest Neighbor (ANN) search algorithms like HNSW (Hierarchical Navigable Small World) and Inverted File Index (IVF).",
        "formula": "$$\\text{HNSW Complexity: } O(\\log N) \\quad \\text{vs Flat Exact Search: } O(N \\cdot d)$$",
        "formula_explanation": "$N$ is total vectors stored and $d$ is embedding dimension. Multi-layer proximity skip-graphs enable searching 100M vectors in under 5 milliseconds.",
        "logic": "Exact brute-force cosine distance search requires computing dot products against every document in the database, which becomes impossible at enterprise scale.",
        "example": "Using Pinecone, Qdrant, or Chroma to store 2 million enterprise HR policies and querying the top 5 most relevant snippets in 12ms."
    },
    {
        "id": "hybrid-search-dense-sparse",
        "topic_id": "genai_rag",
        "topic_label": "Retrieval-Augmented Generation (RAG)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Hybrid Search (Dense + Sparse BM25 Fusion)",
        "raw_sub": "Hybrid Search (Dense Vector Cosine + Sparse BM25 Keyword Search)",
        "definition": "Hybrid search combines the semantic conceptual understanding of dense vector embeddings with the exact keyword matching precision of sparse lexical search (BM25 / SPLADE), fused using Reciprocal Rank Fusion (RRF).",
        "formula": "$$\\text{RRF}(d) = \\sum_{m \\in \\{\\text{dense}, \\text{sparse}\\}} \\frac{1}{k + \\text{rank}_m(d)} \\quad (k \\approx 60)$$",
        "formula_explanation": "$\\text{rank}_m(d)$ is the 1-based rank position of document $d$ in system $m$, and $k$ is a smoothing constant.",
        "logic": "Dense embeddings often fail on exact alphanumeric identifiers (part numbers, serial codes, drug names 'XYZ-9021'). BM25 nails exact strings, while dense vectors nail conceptual synonyms ('head pain' $\\to$ 'migraine').",
        "example": "Searching medical records for patient 'ID-99412 allergy penicillin': BM25 guarantees finding the exact ID, while dense search surfaces relevant clinical allergy documentation."
    },
    {
        "id": "cross-encoder-reranking",
        "topic_id": "genai_rag",
        "topic_label": "Retrieval-Augmented Generation (RAG)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Cross-Encoder Re-ranking",
        "raw_sub": "Cross-Encoder Re-ranking (Rescoring candidate chunks)",
        "definition": "Re-ranking uses a two-stage retrieval pipeline: a fast bi-encoder (vector DB) retrieves top $K=50$ candidates, which are then passed through an intensive cross-encoder model (e.g. Cohere Rerank, BGE-Reranker) that performs joint full self-attention across prompt and passage pairs.",
        "formula": "$$\\text{Score}_{cross}(q, d) = \\text{Transformer}([q; \\text{SEP}; d]), \\quad \\text{vs Bi-Encoder: } \\cos(\\mathbf{e}_q, \\mathbf{e}_d)$$",
        "formula_explanation": "Cross-encoders evaluate all pairwise token interactions between query and candidate document simultaneously, yielding dramatically higher semantic accuracy.",
        "logic": "Bi-encoders compress an entire 500-word document into a single fixed vector, inherently losing fine nuance. Cross-encoders examine every word of query against every word of chunk.",
        "example": "In an enterprise RAG pipeline: vector search fetches 40 candidates; Cross-Encoder rescores and filters down to the top 3 truly authoritative passages, boosting factual accuracy by 25%."
    },
    {
        "id": "hallucination-mitigation-grounding",
        "topic_id": "genai_rag",
        "topic_label": "Retrieval-Augmented Generation (RAG)",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Hallucination Mitigation & Source Grounding",
        "raw_sub": "Hallucination Mitigation & Source Grounding",
        "definition": "Techniques to ensure an LLM generates answers strictly grounded in retrieved evidence rather than fabricating plausible-sounding falsehoods from parametric memory. Includes citation linking, chain-of-verification, and RAG triad evaluation (Context Relevance, Groundedness, Answer Relevance).",
        "formula": "$$\\text{Faithfulness Score} = \\frac{|\\text{Claims in Answer supported by Context}|}{|\\text{Total Claims in Answer}|} \\in [0, 1]$$",
        "formula_explanation": "Using TruLens / Ragas frameworks: automated evaluator models decompose responses into atomic assertions and verify each against source snippets.",
        "logic": "LLMs are statistical sequence completion engines without inherent epistemic awareness of truth. Explicit system instructions ('If the context does not contain the answer, state that you do not know') reduce hallucinations drastically.",
        "example": "Medical RAG assistant appending footnote citations `[Source: Doc 4, p.12]` to every dosage claim, preventing lethal hallucinated drug instructions."
    },

    # genai_prompt_agents
    {
        "id": "in-context-learning-few-shot",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Zero-shot & Few-shot In-Context Learning",
        "raw_sub": "Zero-shot & Few-shot In-Context Learning",
        "definition": "In-Context Learning (Brown et al., 2020) allows pre-trained LLMs to execute new tasks without parameter weight updates simply by conditioning on task instructions (Zero-shot) or a few input-output demonstration pairs (Few-shot) inside the prompt.",
        "formula": "$$P(y_{test} \\mid x_{test}, \\,(x_1, y_1), \\,(x_2, y_2), \\dots, \\,(x_k, y_k))$$",
        "formula_explanation": "$k$ is the number of exemplars (shots). In-context attention mechanisms infer latent task functions directly on the forward pass activations.",
        "logic": "Few-shot examples steer model activations into the desired output distribution and format (e.g. valid JSON) without triggering catastrophic forgetting or fine-tuning infrastructure costs.",
        "example": "Prompting: 'Translate English to SQL. Input: show active users -> Output: SELECT * FROM users WHERE active=1; Input: count orders -> Output: [Model completes correctly]'."
    },
    {
        "id": "chain-of-thought-cot",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Chain of Thought (CoT Reasoning)",
        "raw_sub": "Chain of Thought (CoT - 'Let's think step by step')",
        "definition": "Chain of Thought (Wei et al., 2022) prompts language models to decompose complex multi-step reasoning problems into intermediate natural language deduction steps before arriving at a final answer (e.g. 'Let's think step by step').",
        "formula": "$$P(\\text{Answer} \\mid \\text{Question}) = \\sum_{\\text{Steps}} P(\\text{Answer} \\mid \\text{Question}, \\text{Steps}) \\cdot P(\\text{Steps} \\mid \\text{Question})$$",
        "formula_explanation": "Allocates intermediate test-time compute tokens, expanding the working computational budget of the transformer forward passes.",
        "logic": "Transformers perform a fixed amount of computation per output token. Asking for an instant answer forces a 1-step guess. Generating intermediate thought tokens allows the model to store partial state and work through algorithmic logic.",
        "example": "Math word problem: 'A store has 15 apples. It sells 6, buys 10, then drops 2. How many are left?' CoT writes out $15-6=9 \\to 9+10=19 \\to 19-2=17$, avoiding careless arithmetic errors."
    },
    {
        "id": "react-framework-reasoning-action",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "ReAct Framework (Reasoning + Acting)",
        "raw_sub": "ReAct Framework (Reasoning + Acting in iterative loops)",
        "definition": "The ReAct framework (Yao et al., 2022) combines reasoning traces and task-specific external tool actions in an interleaved loop: Thought (verbal reason about situation) $\\to$ Action (call tool) $\\to$ Observation (receive tool output) $\\to$ Repeat until goal is achieved.",
        "formula": "$$\\mathcal{T}_{t+1} = [\\tau_t; \\, \\text{Thought}_t; \\, \\text{Action}_t; \\, \\text{Observation}_t]$$",
        "formula_explanation": "$\\tau_t$ is the historical context trace, augmented with each new observation to ground subsequent reasoning steps.",
        "logic": "Pure reasoning models suffer from hallucination and lack current environment information. Pure action models lack strategic long-term planning. ReAct combines dynamic thought planning with environmental feedback.",
        "example": "Agent looking up weather: Thought: 'I need current temperature in Tokyo.' Action: `weather_api('Tokyo')`. Observation: `'22°C, Rain'`. Thought: 'Now I should advise an umbrella.' Final Response: 'It is 22°C and rainy in Tokyo, bring an umbrella!'"
    },
    {
        "id": "function-calling-tool-use",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Function Calling & Tool Use",
        "raw_sub": "Function Calling & Tool Use (APIs, Code Interpreters, SQL)",
        "definition": "Function calling equips LLMs with JSON schemas defining available software tools (APIs, databases, bash shells, calculators). The model generates structured machine-readable JSON function calls instead of text, which an executor environment runs and returns results for.",
        "formula": "$$\\text{Schema}(F) \\to \\text{LLM Output: } \\{\\text{\"name\": } \"get\\_stock\\_price\", \\text{\"arguments\": } \\{\\text{\"symbol\": } \"GOOGL\"\\}\\}$$",
        "formula_explanation": "Fine-tuned models strictly conform to JSON Schema specifications, enabling reliable deterministic software integration.",
        "logic": "Allows models to break out of the static knowledge frozen at training time, performing real-world actions like running unit tests, sending emails, or querying live SQL databases.",
        "example": "User asks: 'Calculate $893 \\times 4291$'. Instead of guessing, the LLM emits a function call `python_interpreter(expr='893 * 4291')`, receiving exact answer `3831863`."
    },
    {
        "id": "agent-memory-architectures",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Agent Memory Architectures",
        "raw_sub": "Agent Memory (Short-term working context + Long-term vector memory)",
        "definition": "Agent memory architectures divide state storage into Short-term Memory (the active conversational context window and scratchpad) and Long-term Memory (an external vector database storing episodic past experiences and semantic user profiles retrieved via similarity).",
        "formula": "$$\\text{Context}_{t} = [\\text{System Prompt}; \\, \\text{Working Memory}; \\, \\text{Retrieved Long-Term Memories}(q)]$$",
        "formula_explanation": "Past experiences are retrieved using a scoring function combining Recency, Importance, and Semantic Relevance (Park et al., 2023).",
        "logic": "Context windows are limited and transient. Long-term memory allows autonomous agents to remember user preferences across sessions, learn from past trial-and-error mistakes, and maintain coherent persona.",
        "example": "Personal coding assistant recalling: 'User prefers type annotations and pytest syntax' from a conversation held three weeks prior."
    },
    {
        "id": "multi-agent-orchestration",
        "topic_id": "genai_prompt_agents",
        "topic_label": "Prompt Engineering & Autonomous Agents",
        "category": "genai",
        "category_label": "Generative AI & LLMs",
        "title": "Multi-Agent Orchestration",
        "raw_sub": "Multi-Agent Orchestration (Specialized agents collaborating)",
        "definition": "Multi-agent systems (AutoGen, CrewAI, LangGraph) structure complex tasks across multiple specialized autonomous agents (e.g. Planner, Coder, Reviewer, Tester) communicating through message protocols, state machines, or blackboard architectures.",
        "formula": "$$\\mathcal{M} = \\langle \\{A_1, A_2, \\dots, A_k\\}, \\Sigma, \\delta, \\Pi \\rangle$$",
        "formula_explanation": "$A_i$ are specialized agent personas with custom tools and system prompts, $\\Sigma$ is the shared state space, $\\delta$ is the transition graph, and $\\Pi$ is the communication protocol.",
        "logic": "A single monolithic prompt struggles to maintain focus across multifaceted workflows. Dividing responsibilities allows each agent to adopt a specialized persona and critique each other's work.",
        "example": "Software development workflow: Architect agent designs module schemas $\\to$ Developer agent writes Python implementation $\\to$ QA agent runs tests in a sandbox and sends bug reports back until all tests pass."
    }
]

if __name__ == "__main__":
    print(f"Loaded {len(GENAI_CONCEPTS)} Generative AI concepts successfully.")
