import React, { createContext, useContext, useState, useEffect, useMemo } from 'react';

const ProgressContext = createContext();

const STORAGE_KEYS = {
  COMPLETED: 'the_era_of_ai_completed',
  BOOKMARKS: 'the_era_of_ai_bookmarks',
  NOTES: 'the_era_of_ai_notes'
};

export function ProgressProvider({ children }) {
  // Set of completed item IDs
  const [completedItems, setCompletedItems] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEYS.COMPLETED);
      return saved ? new Set(JSON.parse(saved)) : new Set();
    } catch {
      return new Set();
    }
  });

  // Array of bookmarked items: { id, type, title, subtitle, link, addedAt }
  const [bookmarkedItems, setBookmarkedItems] = useState(() => {
    try {
      const saved = localStorage.getItem(STORAGE_KEYS.BOOKMARKS);
      return saved ? JSON.parse(saved) : [];
    } catch {
      return [];
    }
  });

  // Persist completed items
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEYS.COMPLETED, JSON.stringify(Array.from(completedItems)));
    } catch (e) {
      console.error('Failed to save completed items', e);
    }
  }, [completedItems]);

  // Persist bookmarks
  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEYS.BOOKMARKS, JSON.stringify(bookmarkedItems));
    } catch (e) {
      console.error('Failed to save bookmarks', e);
    }
  }, [bookmarkedItems]);

  const toggleCompleted = (id) => {
    if (!id) return;
    setCompletedItems((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  };

  const isCompleted = (id) => completedItems.has(id);

  const toggleBookmark = (item) => {
    if (!item || !item.id) return;
    setBookmarkedItems((prev) => {
      const exists = prev.some((b) => b.id === item.id);
      if (exists) {
        return prev.filter((b) => b.id !== item.id);
      } else {
        return [
          {
            ...item,
            addedAt: new Date().toISOString()
          },
          ...prev
        ];
      }
    });
  };

  const isBookmarked = (id) => bookmarkedItems.some((b) => b.id === id);

  const removeBookmark = (id) => {
    setBookmarkedItems((prev) => prev.filter((b) => b.id !== id));
  };

  const clearBookmarks = () => {
    setBookmarkedItems([]);
  };

  // Export all bookmarks to downloadable markdown cheatsheet
  const exportBookmarksToMarkdown = () => {
    if (bookmarkedItems.length === 0) return;

    let md = `# The Era of AI — Personalized Study Guide & Cheatsheet\n`;
    md += `*Generated on: ${new Date().toLocaleDateString()}*\n\n`;
    md += `## 📚 Saved Bookmarks (${bookmarkedItems.length} items)\n\n`;

    const byType = {
      concept: bookmarkedItems.filter((b) => b.type === 'concept'),
      paper: bookmarkedItems.filter((b) => b.type === 'paper'),
      interview: bookmarkedItems.filter((b) => b.type === 'interview'),
      syllabus: bookmarkedItems.filter((b) => b.type === 'syllabus')
    };

    if (byType.concept.length > 0) {
      md += `### 💡 Core Concepts\n`;
      byType.concept.forEach((c) => {
        md += `- **${c.title}**${c.subtitle ? ` — ${c.subtitle}` : ''}\n`;
      });
      md += `\n`;
    }

    if (byType.paper.length > 0) {
      md += `### 📄 Landmark Research Papers\n`;
      byType.paper.forEach((p) => {
        md += `- **${p.title}**${p.subtitle ? ` (${p.subtitle})` : ''}\n`;
      });
      md += `\n`;
    }

    if (byType.interview.length > 0) {
      md += `### 🎯 Technical Interview Questions\n`;
      byType.interview.forEach((q) => {
        md += `- **${q.title}**\n  *Category: ${q.subtitle || 'Interview'}*\n`;
      });
      md += `\n`;
    }

    if (byType.syllabus.length > 0) {
      md += `### 🗺️ Syllabus Modules\n`;
      byType.syllabus.forEach((s) => {
        md += `- **${s.title}**${s.subtitle ? ` — ${s.subtitle}` : ''}\n`;
      });
      md += `\n`;
    }

    md += `---\n*Generated by The Era of AI — Master Knowledge Graph & Portal*\n`;

    const blob = new Blob([md], { type: 'text/markdown;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `The-Era-of-AI-Cheatsheet-${new Date().toISOString().slice(0, 10)}.md`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <ProgressContext.Provider
      value={{
        completedItems,
        completedCount: completedItems.size,
        toggleCompleted,
        isCompleted,
        bookmarkedItems,
        bookmarkCount: bookmarkedItems.length,
        toggleBookmark,
        isBookmarked,
        removeBookmark,
        clearBookmarks,
        exportBookmarksToMarkdown
      }}
    >
      {children}
    </ProgressContext.Provider>
  );
}

export function useProgress() {
  const context = useContext(ProgressContext);
  if (!context) {
    throw new Error('useProgress must be used within a ProgressProvider');
  }
  return context;
}
